/* Batomon Companion — curated strategy content.
 * Grounded in: batodex.com live data + Master Ranked win rates, Steam patch notes
 * 0.5.0→0.8.4, itch devlogs, press coverage. Heuristic parts are labeled.
 */
window.GUIDE = {

  // Patch/meta-informed monster adjustments used by the engine (mult 0.8–1.25).
  MONSTER_META_ADJ: {
    bambudo:    { mult: 1.15, note: 'Buffed 0.8.0 (+35/cast) — community-famous carry' },
    emperooze:  { mult: 1.1,  note: 'Free stats every battle start' },
    sunsage:    { mult: 1.12, note: 'CDS engine for Fire boards' },
    gildshell:  { mult: 1.1,  note: 'Shiny version converts economy into damage' },
    prismagon:  { mult: 1.12, note: 'Buffed 0.8.0 — rainbow boards love it' },
    noxalith:   { mult: 1.08, note: 'Buffed 0.8.0 poison feed' },
    thorntail:  { mult: 1.1,  note: 'Buffed twice (0.6.0, 0.8.0)' },
    coalem:     { mult: 1.08, note: 'Shield numbers buffed 0.8.0' },
    wishwash:   { mult: 1.08, note: 'Buffed 0.8.0 — free trinket + sell value' },
    galvanine:  { mult: 1.08, note: 'CD buffed 0.8.0' },
    torrantler: { mult: 1.12, note: 'CD 10→8 in 0.8.0 — Water engine core' },
    geminiss:   { mult: 0.92, note: 'Nerfed 0.8.0 (shield 50/100/150%)' },
    infernade:  { mult: 0.95, note: 'Burn nerfed 0.8.0 (as Pyronade)' },
    reapra:     { mult: 0.95, note: 'CD nerfed 0.8.0' },
    dragonarch: { mult: 1.2,  note: 'x24 Multicast at L4 — premier finisher' },
    gaiadrasil: { mult: 1.15, note: 'Copies adjacent damage — scales with any board' },
    omnichrome: { mult: 1.2,  note: 'Steals enemy stats — always relevant' },
    faebloom:   { mult: 1.12, note: '0.8.0 flagship — item builds' },
    riglet:     { mult: 1.1,  note: 'Devour → Rigalord duplication engine' },
    celestia:   { mult: 1.05, note: 'Disables Ongoing carries (Gaiadrasil etc.)' },
    stalagrove: { mult: 1.08, note: 'Buffed 0.8.0 — shield-to-damage payoff' },
    shelldra:   { mult: 1.1,  note: 'Self-ramping multicast every 4s' },
    humbolt:    { mult: 0.95, note: 'Reworked to damage; no longer a shock bot' },
  },

  // ---------------- Day-by-day coaching ----------------
  DAYS: [
    {
      day: 1, title: 'Foundation — buy tempo, not dreams',
      plan: [
        'Spend everything. Gold sitting idle on day 1 is a lost battle on day 2 (there is no base interest; only Piggy Bank pays interest).',
        'Best day-1 buys are cheap Commons with self-scaling text: Bambudo (+35 Dmg/cast, permanently), Emperooze line via Dribblet, Mosslug, Bumblebolt (Shock starter).',
        'If your trainer grants a unit (Monster Ranger — 61.4% real win rate), build around merging that species: you get another copy every 2 days for free.',
        'Grab evolution seeds NOW: Dribblet/Scorchimp/Panbud need a deep stack to evolve (L3 = 9 copies under the 3-merge rule), so every early copy compounds — start hoarding by day 4-6.',
      ],
      lineup: 'Put your only real attacker top-middle (crown trinkets target that slot later). Healer/utility bottom row.',
      items: 'Use your free item slots on $0 items (Cake, Feast, tickets). Never end the day with unused free rerolls (Youngster gets 3).',
      warning: 'Do NOT skip buying to "save for a Rare" — day-1 losses cost lives and shop tempo.',
    },
    {
      day: 2, title: 'Pairs — start your first merge',
      plan: [
        'Priority #1: stack copies of your day-1 units — THREE of the same make a Level 2 (two do not merge), and an early Level 2 wins fights on stats alone by day 3-4.',
        'Bug boards: every Bug you buy pumps Guardiant (+7 Dmg), Cinderfly and Shogapede (+10% CDS). Bug Catcher (59.9% WR) makes the first Bug each round FREE.',
        'Chef (57.9% WR) runs: single-typed units become Fire — pick up burn bodies early (Magmite, Scorchimp line).',
        'Sell nothing yet unless the bench is full — copies are merge fuel.',
      ],
      lineup: 'Keep attackers where they connect; "ally above/behind" texts care about columns — read your units\' positional words before locking.',
      items: 'Green Stone a spare Common into an Uncommon if the shop is dry. Fake Coin/Lucky Coin are free value.',
      warning: 'Musician (55.4% WR): keep EXACTLY one Electric. A second Electric turns +150% Shock OFF.',
    },
    {
      day: 3, title: 'First Level 2 window',
      plan: [
        'Merge your strongest trio to Level 2 — 3 copies of the same level combine into ONE (two copies do NOT merge). Level-3 evolvers (Dribblet→Emperooze, Scorchimp→Sunsage, Panbud→Bambudo) jump a whole power band but L3 needs 9 copies (or level-up items), so they are a deeper commit.',
        'Once a species hits L3, its pre-evolutions vanish from your shop (0.7.4) — but L3 = nine copies, so commit hard to that species or lean on level-up items (Upgrade Disc) to get there.',
        'Start committing to an archetype: check what the shop keeps handing you (poison feed → Chemist package; shields → Rock wall).',
        'Trinket gift? Take economy or Treasure Map early: Treasure Map upgrades your NEXT gift a full rarity tier.',
      ],
      lineup: 'Trigger-chains come online: Cicadence under a Bug, Dryadell under a Grass unit, Voltalith feeding Shock upward.',
      items: 'Basic Candy ($30) can force the L3 if the shop refuses to cooperate.',
      warning: 'Don\'t hold 3 different half-pairs into day 4 — pick two lines and fund them.',
    },
    {
      day: 4, title: 'Shop rank decision',
      plan: [
        'Either rank UP (Apex Bait $20, Market License trinket, Rich Lady start) to fish Rares/Super Rares — or deliberately rank DOWN (Basic Bait $0) to finish Common/Uncommon merges.',
        'Rank-down is the underrated play if you still need copies for an evolution or a L4 push.',
        'Strong Rare pickups: Ironcore (charges Electrics), Formiqueen (Common CDS aura), Lignite (burn multiplier), Aristobat (poison multicast).',
        'Egg Breeder\'s Purple Egg hatches tomorrow (5 days) — keep a slot free.',
      ],
      lineup: 'Depth logic hardens: the RIGHT column is the front (enemy side) and takes hits first. Shields in the right column, ramping casters to the LEFT (behind).',
      items: 'Rarity tickets (Gray/Green/Blue) force a whole shop of one rarity — use them to dig for exact copies.',
      warning: 'Stop buying one-of units "because they look strong" — every non-merge purchase must have a job (economy, trigger piece, or evolution seed).',
    },
    {
      day: 5, title: 'Engine assembly',
      plan: [
        'Your board should name its win condition today: Burn ramp / Poison quadratic / Shock amp / Shield fortress / Multicast feed / Economy snowball.',
        'Buy the ENABLERS now, payoffs later: Noxalith feeds poison up a column, Magmalith feeds burn, Boomagon feeds CDS, Zephyrex feeds Multicast to the front.',
        'Real trinket data for this phase: Silver Watch 62.3-band, Warhorn, Meteorite all strong (see Trinkets tab, sorted by real win rate).',
        'Swim Coach (56.5% WR) gets a free Water unit daily — Torrantler later turns those into a chain gun.',
      ],
      lineup: 'Adjacency payoffs (Aster, Noxnimbus, Formiqueen) want to sit in the middle column — maximum neighbours.',
      items: 'Coffee ($5) doubles On-Battle-Start abilities for one fight — bank it for a badge fight you might lose.',
      warning: 'Losing on purpose is never free (lives), but a planned loss while assembling beats selling your engine for one win.',
    },
    {
      day: 6, title: 'Rare→Super Rare transition',
      plan: [
        'Shop rank should let Super Rares appear. Premier targets: Shelldra (self-multicast), Coalem (buffed), Aegistruct (shield copy), Prismagon (rainbow scaling), Wishwash (free trinket).',
        'Level 4 conversations start: a 4th copy of your carry is usually worth more than any new unit (L4 = Multicast or ~8x stat spikes).',
        'VIP Pass trinket removes Common/Uncommon from your shop — take it only AFTER your merges are done.',
        'Mad Scientist runs: tomorrow everything on the active team becomes random L1 Legendaries — dump gold into board slots, not levels.',
      ],
      lineup: 'Celestia check: if enemies run Ongoing carries (Gaiadrasil/Lignite/Fumungus), Celestia front-row disables their row.',
      items: 'Recruiting Flyer ($90) = instant L3 Uncommon; strongest when it completes a type package.',
      warning: 'Champion pace check: you want a stable 5-6 unit board with 1-2 units at L3+ by end of day 6.',
    },
    {
      day: 7, title: 'Legendary window / Mad Scientist day',
      plan: [
        'Legendaries in shops now: Torrantler (Water engine), Gaiadrasil (damage mirror), Galvanine (buffed), Stellagon (+2 Multicast to no-ability allies), Draconarch ($60 — the L4 x24 dream).',
        'MAD SCIENTIST: transformation fires today — every active slot becomes a random L1 Legendary. Fill all six slots BEFORE the transform.',
        'Stellagon tech: no-ability stat-sticks (Joltail, Magmite, Velocect, Blazewing, Aristobat) suddenly double-cast.',
        'Lootbox item ($30): random Legendary — good gold-to-power conversion this exact day.',
      ],
      lineup: 'Draconarch wants On-Battle-Start neighbours (Emperooze, Coalem, Aegistruct, Warhorn-style effects) — he re-triggers them every cast.',
      items: 'Rare Candy ($40) any L1 → L2. Ultra Candy ($60) pushes an L3 to L4 — save for your true carry.',
      warning: 'Do not break a working engine for a random Legendary — a L3 synergy core usually beats a lonely L1 Legendary.',
    },
    {
      day: 8, title: 'Level 4 push',
      plan: [
        'L4 spikes win championships: Draconarch x24 Multicast, Celestia 3120 dmg, Aristobat x8 poison, Basilord 1s cooldown.',
        'Ignit line check: Ignit→Flarilisk→Basilord evolves ON VICTORY — it needs win streaks; if you\'re losing, it stalls.',
        'Trinket gifts here should be payoff-tier. Real win rates: Excalibur 76.1%, Master Crown 74.9%, Ultra Duplicator 73.1%, Holy Grail 72.2%, Zenith Stone 69.4%.',
        'Zenith Stone note: +80% on ALL stat gains — multiplies your ramping units (Bambudo, Thorntail, Prismagon, Omnichrome).',
      ],
      lineup: 'Crown check: Power/Haste/Winged/Master Crown all point at TOP-MIDDLE. Your carry sits there, full stop.',
      items: 'Shiny Berry ($1): random unit turns SHINY (+~20% + upgraded ability) AND refunds an item use. Near-mandatory buy.',
      warning: 'Gamer trainer: the free Mythical + $30 lands tomorrow (day 9) — don\'t sell board slots you\'ll want to keep.',
    },
    {
      day: 9, title: 'Mythical access / closing power',
      plan: [
        'Mythicals appear via trainers, trinkets, events — not normal shops. Mystic Incense trinket forces one into your next shop.',
        'Omnichrome ($80) steals 240%+ of the enemy\'s best unit\'s stats at L3 — it scales with THEIR board, never a dead pick.',
        'Faebloom item build: Mythical Items appear in your shop; adjacent allies gain +Dmg per Mythical Item used (Shopkeeper trainer supercharges this).',
        'Riglet devours the ally in front tomorrow — feed it something whose copies you want Rigalord to spawn.',
      ],
      lineup: 'Rigalord spawns copies in the BOTTOM row — leave bottom slots open on the day it comes online.',
      items: 'Crimson Gift ($70) = random Mythical trinket. Magic Lasso ($50) copies the enemy\'s top-middle for the next fight — scout, then steal.',
      warning: 'Championship is at 10 badges — count your badges and lives; a greedy pivot on day 9 loses finished runs.',
    },
    {
      day: 10, title: 'Championship / Extended decision',
      plan: [
        'Badge 10 = championship. Win with your carry at L3+ for the Batopedia Medal; win with a Shiny for the Star.',
        'Extended Mode (0.7.2): runs can continue to day 40 — stat cap is 999,999,999 (0.7.4). Quadratic scalers (Poison, Omnichrome, Bambudo/Thorntail ramps) rule the long game.',
        'Post-10 shops: Crimson Ticket ($50) rerolls an all-Mythical shop; Research Notes trinket floods Legendaries.',
        'Duplicator stack (Ultra Duplicator 73.1% WR) + Treasure Map turns every gift into multiple top-tier trinkets.',
      ],
      lineup: 'Final check — top-middle carry crowned, On-Battle-Start batteries adjacent to Draconarch, Ongoing units away from enemy Celestia rows.',
      items: 'Spend to zero before the final fight. Unspent gold wins nothing.',
      warning: 'Two L4 shiny legendaries is a known "game over" board — if you see the pieces, commit everything.',
    },
  ],

  // ---------------- Build archetypes ----------------
  BUILDS: [
    {
      id: 'burn', name: 'Burn Engine', icon: 'infernade',
      trainer: 'pyromaniac', altTrainers: ['redhead'],
      difficulty: 'Easy', power: 'A',
      core: ['scorchimp', 'magmite', 'magmalith', 'lignite', 'blazewing', 'infernade'],
      lateCore: ['ignit', 'flarilisk', 'basilord', 'blixie', 'coalem'],
      trinkets: ['fire_orb', 'warhorn', 'zenith_stone', 'excalibur'],
      items: ['hot_pepper', 'coffee', 'rare_candy'],
      how: 'Chef converts single-typed units to Fire (+2 Burn each). Magmalith pumps permanent Burn up its column into Lignite, whose Ongoing turns every Burn stack into +15 flat damage. Scorchimp→Sunsage gives the whole Fire row Cooldown Speed. Late game the Ignit victory-chain becomes Basilord: 450 Burn at a 1-second cooldown at L4. Redhead runs the same shell as a scaling ENGINE instead: no type conversion, but every Victory permanently adds +2 Burn to each Fire monster — so field real Fire bodies early and each win compounds their burn all run.',
      lineup: { top: ['lignite', 'basilord', 'sunsage'], bottom: ['magmalith', 'blixie', 'magmite'] },
      dayplan: 'D1-2 Scorchimp copies + Magmite bodies · D3 Sunsage online · D4-5 Magmalith/Lignite column · D6+ Ignit the moment you are winning streaks · D8 Ultra Candy the carry.',
      counters: 'Burn decays — heavy Heal/Shield boards (Aster, Coalem walls) outlast sloppy burn. Keep Lignite as the flat-damage insurance.',
    },
    {
      id: 'poison', name: 'Poison Quadratic', icon: 'noxalith',
      trainer: 'chemist', altTrainers: ['masked_man'],
      difficulty: 'Medium', power: 'S (long fights)',
      core: ['venopuff', 'spinarai', 'noxnimbus', 'noxalith', 'thorntail', 'aristobat'],
      lateCore: ['cobrex', 'fumungus', 'puffloon'],
      trinkets: ['poison_orb', 'zenith_stone', 'silver_watch'],
      items: ['black_sludge', 'basic_candy', 'ultra_candy'],
      how: 'Poison never decays and ticks every second — damage grows quadratically with fight length. Chemist adds +1 Poison to ALL Toxic units per ANY level-up (it compounds). Noxalith feeds +3 permanent Poison up its column, Thorntail converts every ally poison application into permanent +6 damage, Aristobat at L4 is 16 poison x8 multicast, Cobrex charges itself off every poison tick. Fumungus deals bonus damage equal to enemy poison.',
      lineup: { top: ['thorntail', 'aristobat', 'fumungus'], bottom: ['noxalith', 'cobrex', 'noxnimbus'] },
      dayplan: 'D1-2 Venopuff/Spinarai bodies · D3-4 level ANYTHING (Chemist stacks) · D5 Noxalith column + Thorntail · D7 Cobrex · D8+ fights are long, you win the math.',
      counters: 'Runerock/Sirenade cleanse stacks; fast burst boards end fights before the curve pays. Sequence tip (0.7.3): shield absorbs status at 75% — expect slower starts vs Rock walls.',
    },
    {
      id: 'shock', name: 'Solo-Electric Shock (Musician)', icon: 'galvanine',
      trainer: 'musician', altTrainers: ['masked_man'],
      difficulty: 'Hard', power: 'A',
      core: ['bumblebolt', 'joltail', 'ironcore', 'clawnetic', 'pylong'],
      lateCore: ['galvanine'],
      trinkets: ['power_crown', 'haste_crown', 'winged_crown', 'master_crown'],
      items: ['battery_pack', 'rare_candy', 'ultra_candy'],
      how: 'Musician: EXACTLY one Electric on the team gets +150% Shock. Shock permanently amplifies every direct hit on the target. Run ONE Electric carry (Galvanine end-state: +50% CDS and +2 Shock per cast, self-snowballing) supported by non-Electric hitters. Ironcore charges it (Steel, not Electric — legal), Clawnetic charges itself off every Shock application, Pylong doubles the Shock of the unit behind... but Pylong is Electric — slot it ONLY if you drop the Musician bonus intentionally.',
      lineup: { top: ['clawnetic', 'galvanine', 'shelldra'], bottom: ['ironcore', 'pylong', 'aristobat'] },
      dayplan: 'D1 Bumblebolt/Joltail (pick ONE line) · D3 sell the spare Electric before it breaks the bonus · D5 Ironcore · D7 Galvanine and full crown stack top-middle.',
      counters: 'Shock only boosts DIRECT damage — pure status boards ignore it. Knockout effects on your single carry are catastrophic: Cherubble Protect tech helps.',
    },
    {
      id: 'wall', name: 'Shield Fortress → Stalagrove', icon: 'aegistruct',
      trainer: 'lady', altTrainers: ['youngster_m'],
      difficulty: 'Easy', power: 'B+',
      core: ['pebbler', 'runerock', 'cherubble', 'stalagrove', 'coalem'],
      lateCore: ['aegistruct', 'geminiss'],
      trinkets: ['topaz_amulet', 'barbell', 'meteorite'],
      items: ['shiny_pebble', 'basic_candy'],
      how: 'Stack Shield until the enemy cannot dent you, then let Stalagrove convert 15% of every shield received into damage. Coalem (buffed 0.8.0: 450/900/1350 shield) triggers itself on battle start; Aegistruct copies adjacent shields; Geminiss multiplies the row. Status damage is reduced 25% into shields and Poison no longer bypasses (0.6.0) — walls are real.',
      lineup: { top: ['coalem', 'aegistruct', 'stalagrove'], bottom: ['pebbler', 'geminiss', 'runerock'] },
      dayplan: 'D1-2 Pebbler pairs · D3 Cherubble Protect · D5 Stalagrove BEFORE the big shield units · D6-7 Coalem/Aegistruct wall · Runerock answers poison boards.',
      counters: 'Pure Heal-cut or massive single hits (Celestia L4, Draconarch trains). Slow to close — pair with one true carry.',
    },
    {
      id: 'multicast', name: 'Draconarch Multicast Train', icon: 'dragonarch',
      trainer: 'lady', altTrainers: ['treasure_hunter', 'youngster_m'],
      difficulty: 'Hard', power: 'S',
      core: ['boomagon', 'dracana', 'shelldra', 'saberhorn'],
      lateCore: ['dragonarch', 'zephyrex', 'stellagon', 'onsetra'],
      trinkets: ['winged_crown', 'repeater_charm', 'master_crown', 'metronome'],
      items: ['coffee', 'black_feather', 'ultra_candy'],
      how: 'Draconarch re-activates the On-Battle-Start abilities of adjacent allies EVERY cast, and at L4 casts x24. Surround him with battle-start batteries (Emperooze, Coalem, Warhorn effects, Omnichrome!). Boomagon feeds permanent Cooldown Speed to the ally on his RIGHT (in-game arrow) — park Boomagon directly LEFT of Draconarch, Dracana/charge units accelerate the loop, Saberhorn/Zephyrex hand out +1 Multicast, Stellagon gives stat-sticks +2 Multicast. Repeater Charm + Coffee double all openers.',
      lineup: { top: ['emperooze', 'dragonarch', 'omnichrome'], bottom: ['boomagon', 'dracana', 'coalem'] },
      dayplan: 'D1-3 tempo Commons (Emperooze line doubles as battery) · D5 Boomagon/Dracana rails · D7 Draconarch ($60) · D8-9 crowns + Repeater Charm · D10 x24 goes brrr.',
      counters: 'Knockout snipes on Draconarch; Celestia disabling your Ongoing supports. Keep Cherubble Protect or a decoy row.',
    },
    {
      id: 'econ', name: 'Sell-Value Economy (Shiny Gildshell)', icon: 'gildshell',
      trainer: 'lady', altTrainers: ['shopkeeper', 'bug_catcher'],
      difficulty: 'Medium', power: 'B (A with shiny)',
      core: ['gildshell', 'plunderbird', 'berroon', 'wishwash'],
      lateCore: ['goldora', 'faebloom'],
      trinkets: ['piggy_bank', 'gold_bar', 'membership_card', 'holy_grail'],
      items: ['gold_powder', 'lucky_coin', 'tote_bag'],
      how: 'Gildshell gains permanent Sell Value every battle; the SHINY version deals bonus damage equal to 0.5x its Sell Value — your bank account becomes a weapon. Gold Powder (+20 sell value, daily) feeds it directly. Plunderbird prints gold per cast, Berroon raises your daily item limit, Wishwash pays a trinket every fight. Convert the treasury into candies and crowns.',
      lineup: { top: ['wishwash', 'gildshell', 'plunderbird'], bottom: ['berroon', 'goldora', 'faebloom'] },
      dayplan: 'D1-2 Gildshell pairs (PRAY for shiny; Shiny Berry it later) · D3-4 Piggy Bank + gold trinkets · D6 you out-buy every opponent · D8+ Goldora mints Legendary trinkets per Legendary ally.',
      counters: 'Raw tempo boards kill you around day 4-6 — keep one real frontline. The build is the shop, not the board.',
    },
    {
      id: 'water', name: 'Torrantler Chain Gun', icon: 'torrantler',
      trainer: 'swim_coach', altTrainers: ['masked_man'],
      difficulty: 'Medium', power: 'A',
      core: ['dribblet', 'mosslug', 'aster', 'sirenade', 'shelldra'],
      lateCore: ['torrantler', 'wishwash', 'dirgefin'],
      trinkets: ['sapphire_amulet', 'silver_watch', 'haste_orb'],
      items: ['mystic_pearl', 'rare_candy'],
      how: 'Swim Coach (56.5% real WR) hands you a free Water unit every day. Torrantler (buffed 0.8.0) triggers ALL adjacent Water allies on cast — center him and every cast becomes a volley. Aster pumps permanent Heal into neighbours, Emperooze (from Dribblet) is a free battery, Shelldra self-multicasts every 4 seconds and loves being triggered early.',
      lineup: { top: ['shelldra', 'torrantler', 'emperooze'], bottom: ['aster', 'wishwash', 'sirenade'] },
      dayplan: 'D1 Dribblet pairs · D3 Emperooze · D4-5 Aster + free daily Water merges · D7 Torrantler center · D9 second Torrantler is NOT adjacent-legal (excludes itself) — diversify.',
      counters: 'Burn pressure out-paces sustain early; Celestia rows disable Ongoing supports. Sirenade cleanse covers the status matchups.',
    },
    {
      id: 'items', name: 'Mythical Item Machine (Faebloom)', icon: 'faebloom',
      trainer: 'shopkeeper', altTrainers: ['lady'],
      difficulty: 'Spicy', power: 'S (post-0.8.0)',
      core: ['berroon', 'alpinine', 'wishwash'],
      lateCore: ['faebloom', 'goldora', 'cosmivore'],
      trinkets: ['echo_bell', 'membership_card', 'vip_pass', 'mystic_incense'],
      items: ['tote_bag', 'lucky_coin', 'nana_berry', 'shiny_berry', 'crimson_gift'],
      how: 'Shopkeeper stocks items a rarity higher at 15% off. Berroon raises the daily item cap per battle start; Tote Bag/Lucky Coin/Nana Berry/Shiny Berry all REFUND uses; Echo Bell double-fires every $0 item. Alpinine gains +20 Damage AND Shield per item used. Faebloom unlocks Mythical Items in your shop and pays adjacent allies +10% damage per Mythical Item used — the loop feeds itself.',
      lineup: { top: ['alpinine', 'faebloom', 'wishwash'], bottom: ['berroon', 'cosmivore', 'goldora'] },
      dayplan: 'D1-3 Berroon + Alpinine and every $0 item you can lift · D4 Echo Bell priority gift · D6+ item cap 5-6/day · D9 Faebloom converts the habit into a win condition.',
      counters: 'Needs setup days — aggressive boards punish a slow start. 0.8.3 nerfed Echo Bell to $0-only items: budget accordingly.',
    },
    {
      id: 'bugchain', name: 'Bug Trigger Chain', icon: 'cicadence',
      trainer: 'bug_catcher', altTrainers: ['pyromaniac'],
      difficulty: 'Easy', power: 'S (real data)',
      core: ['guardiant', 'velocect', 'gildshell', 'cicadence', 'shogapede', 'cinderfly'],
      lateCore: ['formiqueen', 'brawlmantis'],
      trinkets: ['terrarium', 'bug_net', 'silver_watch'],
      items: ['shiny_berry', 'basic_candy'],
      how: 'THE measured top-rank engine: Cicadence+Gildshell+Guardiant runs an 86-89% real win rate as a trio. Every Bug you buy pumps Guardiant (+7 Dmg) and speeds up Cinderfly/Shogapede (+10% CDS each). Cicadence re-triggers the Bug ABOVE it every cast — put your fattest Bug there. Formiqueen gives adjacent Commons +33% CDS, Brawlmantis converts victories into permanent Common damage. Bug Catcher makes the first Bug each round FREE — the engine literally pays for itself.',
      lineup: { top: ['guardiant', 'gildshell', 'brawlmantis'], bottom: ['formiqueen', 'cicadence', 'shogapede'] },
      dayplan: 'D1 Guardiant + any Bugs (free one every round!) · D2-3 Gildshell + Cicadence under it · D4 Shogapede/Cinderfly speed · D5+ Formiqueen center-bottom · every buy compounds.',
      counters: 'Commons cap out — convert the tempo lead into a Legendary closer by day 8, or Celestia rows shut your triggers down.',
    },
    {
      id: 'toxweb', name: 'Puffloon Toxic Web', icon: 'puffloon',
      trainer: 'chemist', altTrainers: ['masked_man'],
      difficulty: 'Medium', power: 'A (24% of top runs)',
      core: ['puffloon', 'noxnimbus', 'venopuff', 'spinarai'],
      lateCore: ['aristobat', 'cobrex', 'fumungus'],
      trinkets: ['poison_orb', 'zenith_stone', 'repeater_charm'],
      items: ['black_sludge', 'rare_candy'],
      how: 'Puffloon appears in 24% of ALL top-rank runs (69.5% WR, usually as multiples — avg 1.9 copies). It triggers whenever an adjacent Toxic ally triggers: chain Noxnimbus (adjacent Toxic +2 Poison per cast) and every Puffloon into a web where one cast cascades through the whole cluster. Chemist compounds +1 Poison on ALL Toxic per any level-up. Aristobat multicast turns the stacked poison into a hose; Fumungus deals bonus damage equal to the enemy\'s poison.',
      lineup: { top: ['venopuff', 'puffloon', 'aristobat'], bottom: ['noxnimbus', 'puffloon', 'cobrex'] },
      dayplan: 'D1-2 Venopuff/Spinarai bodies · D3 FIRST Puffloon (buy every copy you see) · D4-5 Noxnimbus adjacency web · D6 second Puffloon cluster · D7+ Cobrex/Fumungus payoff.',
      counters: 'Runerock/Sirenade cleanse; burst boards end the fight before the quadratic pays. Keep the web adjacent — a scattered Puffloon is a dead Puffloon.',
    },
    {
      id: 'knockout', name: 'Kamikaze Knockout Control', icon: 'reapra',
      trainer: 'lady', altTrainers: ['youngster_m'],
      difficulty: 'Spicy', power: 'B+ (tempo)',
      core: ['stingarde', 'galvanade', 'infernade'],
      lateCore: ['reapra', 'dirgefin', 'cherubble'],
      trinkets: ['warhorn', 'meteorite', 'repeater_charm'],
      items: ['coffee', 'lootbox'],
      how: 'The grenade units (Stingarde/Galvanade/Infernade) dump one huge hit then Knockout themselves — pure opening burst. Reapra (70.4% real WR) snipes the enemy OPPOSITE it every cast: park it across from their carry. Dirgefin mass-Knockouts all Commons on BOTH sides — devastating against swarm boards while your board runs Rares. Cherubble\'s Protect keeps your own carry alive through enemy Knockouts.',
      lineup: { top: ['cherubble', 'reapra', 'infernade'], bottom: ['dirgefin', 'galvanade', 'stingarde'] },
      dayplan: 'D1-2 grenades for tempo wins · D4 sell them as they fall off, Dirgefin in · D6 Reapra opposite their carry (drag it to the matching row!) · D8 Cherubble protects the closer.',
      counters: 'Knockout does nothing to boards that out-stat you — this is control, not scaling. Pivot the tempo lead into any A-tier closer by day 8.',
    },
    {
      id: 'devour', name: 'Riglet Devour Engine', icon: 'rigalord',
      trainer: 'gamer', altTrainers: ['treasure_hunter'],
      difficulty: 'Hard', power: 'S (endgame)',
      core: ['bambudo', 'emperooze', 'riglet'],
      lateCore: ['rigalord', 'aerophim'],
      trinkets: ['zenith_stone', 'winged_crown', 'master_crown'],
      items: ['ultra_candy', 'crimson_gift'],
      how: 'Riglet devours the ally directly in FRONT of it at the start of the next day and becomes Rigalord — which then spawns exact copies of the devoured unit in the bottom row every battle. Feed it your most permanently-stacked unit: a Bambudo that has been banking +35 Dmg/cast for six days becomes an army of stacked Bambudos. Zenith Stone (+80% on all stat gains) makes the pre-feed fattening obscene. Aerophim then hands the spawn row +Multicast.',
      lineup: { top: ['emperooze', 'bambudo', 'rigalord'], bottom: ['aerophim', 'riglet', 'bambudo'] },
      dayplan: 'D1-4 fatten Bambudo (permanent stacks) · D7-8 acquire Riglet (Gamer day-9 mythical or Crimson pieces) · place the fattened unit in FRONT of Riglet the day before · D9+ Rigalord prints monsters. Leave bottom slots OPEN for spawns.',
      counters: 'Telegraphed and slow — one bad devour (wrong unit in front!) wastes the run. Celestia disables Rigalord\'s spawns\' row triggers.',
    },
    {
      id: 'omni', name: 'Omnichrome Mirror Closer', icon: 'omnichrome',
      trainer: 'treasure_hunter', altTrainers: ['lady'],
      difficulty: 'Medium', power: 'S (day 9+)',
      core: ['emperooze', 'coalem', 'prismagon'],
      lateCore: ['omnichrome', 'dragonarch', 'celestia'],
      trinkets: ['mystic_incense', 'repeater_charm', 'master_crown'],
      items: ['crimson_ticket', 'ultra_candy', 'coffee'],
      how: 'Omnichrome steals 80/160/240% (L4: 2400%) of the enemy\'s strongest unit\'s stats at battle start, permanently — it scales with THEIR board, so it never falls off. Surround it with On-Battle-Start batteries (Emperooze, Coalem) and let Draconarch re-trigger the steal every cast (×24 at L4 = you become 24 copies of their carry). Prismagon meanwhile banks +10 Dmg per unique type per cast. Celestia shuts down their Ongoing answers.',
      lineup: { top: ['coalem', 'dragonarch', 'celestia'], bottom: ['emperooze', 'omnichrome', 'prismagon'] },
      dayplan: 'D1-5 any solid tempo core (Emperooze line ideal) · D7 Mystic Incense from Treasure Hunter gifts · D9 Omnichrome in · D10+ Draconarch turns one steal into twenty-four.',
      counters: 'Pre-day-9 you are just a normal board — do not sacrifice tempo for the dream. Mirror matches (their Omnichrome) get weird.',
    },
    {
      // Sourced from a Master-rank community framework (noxxit, Steam discussions,
      // 2026-07-08) which rates One-shot "the best regular comp late game". Gaiadrasil
      // appeared in NO curated build despite that — this fills the gap. Positioning
      // below is derived from the printed abilities, not guesswork.
      id: 'oneshot', name: 'One-Shot Mirror (Gaiadrasil)', icon: 'gaiadrasil',
      trainer: 'monster_ranger', altTrainers: ['pyromaniac', 'treasure_hunter'],
      difficulty: 'Hard', power: 'S (late)',
      core: ['lignite', 'gaiadrasil', 'blixie'],
      lateCore: ['coalem', 'basilord', 'infernade'],
      trinkets: ['zenith_stone', 'excalibur', 'mysterious_gem'],
      items: ['hot_pepper', 'rare_candy', 'ultra_candy'],
      how: 'A three-link damage chain, not a pile of stats. Blixie (On Cast) hands its Burn to the Fire ally BEHIND it; Lignite converts Burn into raw Damage at 15× per stack; Gaiadrasil then has "additional Damage equal to 100% of the total Damage of ADJACENT allies" — so it mirrors Lignite\'s inflated number and deletes a board in one cast. Every point of Burn you feed the chain is multiplied twice. Needs Gaiadrasil L2+ and Lignite L3 to come online.',
      lineup: { top: ['gaiadrasil', 'lignite', 'blixie'], bottom: ['coalem', 'basilord', 'infernade'] },
      dayplan: 'D1-4 survive on cheap Fire bodies and stack Burn sources. D5-7 Lignite to L3 — its Damage is 15× its Burn, so Burn feeds are worth more than flat damage. D8+ land Gaiadrasil and seat it TOUCHING Lignite; keep Blixie immediately in FRONT of Lignite (Blixie feeds the ally behind it). Centre slots maximise Gaiadrasil\'s neighbour count — every adjacent ally\'s Damage is copied.',
      counters: 'One huge hit is exactly what Protect (Cherubble) and shield stall are built to eat, and both are common at high Masters. Dirgefin/Reapra can snipe Gaiadrasil before it ever casts. It is slow — you must not bleed out before Gaiadrasil hits L2.',
    },
  ],

  // ---------------- Item tier list (curated — no public per-item win data) ----------------
  ITEM_TIERS: {
    S: [
      ['shiny_berry', 'Turns a unit SHINY (+~20% + often an upgraded ability) and refunds an item use. Free. Buy on sight.'],
      ['ultra_candy', 'L3 → L4 on demand. L4 spikes (x24 Draconarch, 3120 Celestia) end games.'],
      ['rare_candy', 'Any L1 → level up, no rarity limit. Tempo in a bottle.'],
      ['magic_mirror', 'Plain copy of a random L3 ($120) — instant board slot of finished product.'],
      ['coffee', 'Doubles every On-Battle-Start for the next fight. $5 to steal a badge fight.'],
    ],
    A: [
      ['crimson_gift', 'Random Mythical trinket $70 — the real-WR table says Mythical trinkets carry (Excalibur 76.1%).'],
      ['golden_gift', 'Random Legendary trinket $50.'],
      ['lootbox', 'Random Legendary monster $30 — best on day 7+.'],
      ['recruiting_flyer', 'Instant L3 Uncommon — completes type packages on demand.'],
      ['tote_bag', '+2 item uses today — the engine card for item builds.'],
      ['apex_bait', 'Shop rank up $20 — timing tool for the day-6 Super Rare window.'],
      ['basic_candy', 'Random L1 Common/Uncommon level-up $30.'],
    ],
    B: [
      ['voucher', 'Random monster from current shop $5 — gamble merge fuel.'],
      ['golden_ticket', 'All-Legendary reroll — free, day 7+.'],
      ['crimson_ticket', 'All-Mythical reroll $50 — endgame fishing.'],
      ['blue_ticket', 'All-Rare reroll — evolution/merge digging.'],
      ['gold_powder', '+20 Sell Value daily — Shiny Gildshell fuel, otherwise skip.'],
      ['coupon', 'Shop -$5 per monster. Free money on buy days.'],
      ['black_feather', '+1 Multicast, $30 — premium on single-carry boards.'],
      ['feast', 'Team +5 damage, free.'],
      ['lucky_coin', '+$3 AND refunds the use. Always click.'],
      ['nana_berry', 'Bottom-right +5% CDS, refunds use. Always click.'],
    ],
    C: [
      ['cake', 'Two random units +5 dmg. Fine, free.'],
      ['fake_coin', 'Free reroll. Fine.'],
      ['gray_chip', 'Win-next-battle bet, +$5.'],
      ['green_stone', 'Common → random Uncommon transform.'],
      ['battery_pack', 'Electric +1 Shock — solo-shock only.'],
      ['hot_pepper', 'Fire +1 Burn — burn boards only.'],
      ['black_sludge', 'Toxic +1 Poison — poison boards only.'],
      ['mystic_pearl', 'Water +10 Heal.'],
      ['shiny_pebble', 'Rock +20 Shield.'],
      ['basic_bait', 'Shop rank DOWN — niche merge-digging tech, free.'],
      ['red_coin', '+$20 for a LIFE. Desperation only.'],
      ['focus_pill', 'No-ability units +15% CDS (nerfed 0.8.0) — Stellagon boards.'],
      ['dowsing_rod', 'Choose a Common trinket $15 — usually skip.'],
    ],
  },

  // ---------------- Mechanics cheat sheet ----------------
  MECHANICS: [
    ['Board', '2 rows x 3 columns, side-view: enemies are to the RIGHT. "In front" = right neighbour (same row), "behind" = LEFT neighbour, "above" = top-row slot in the same column. Crowns target TOP-MIDDLE; Nana Berry bottom-right; Speed Crest the right (front) column.'],
    ['Levels', 'Merge duplicates 3-to-1: 3 copies = L2, 9 = L3 (evolutions fire at L3). Two copies do NOT merge — they stay separate bodies. L4 comes only from level-up items/candies (Upgrade Disc, etc.), never from merging. L1→L3 stats scale x1/x2/x3; L4 adds Multicast or ~x8 spikes.'],
    ['Shop rule', 'Own a species at L3 → its pre-evolutions stop appearing (0.7.4). L3 needs 9 copies (3-merge rule), so secure the copies you want before committing that deep.'],
    ['Shinies', '~+20% stats, often an extra/upgraded ability, own sprite. Sources: rare shop rolls, Lucky Girl trainer, Shiny Berry item, Rainbow Pearl trinket. 80/88 species have one.'],
    ['Burn', 'Ticks = stacks every 0.5s, loses 1 stack per tick. Front-loaded, decays.'],
    ['Poison', 'Ticks = stacks every 1s, NEVER decays. Quadratic in fight length.'],
    ['Shock', 'Permanent amp: direct hits on the target gain +stacks damage. Only direct damage.'],
    ['Shield vs status', 'Status damage is reduced 25% against Shield; Poison no longer bypasses Shield (0.6.0).'],
    ['Same-tick order', 'Shield → Damage → Status → Heal (0.7.3). Heal resolves last — it can save from lethal in the same tick.'],
    ['Cooldown Speed', '+100% CDS = casts twice as often. Replaced all flat CD reduction (June 11 update). Floor: 0.1s; UI marks the 1s soft floor.'],
    ['Multicast', 'Casts N times, 0.1s apart. THE level-4 mechanic.'],
    ['Daily items', 'Item uses per day are capped. Berroon (+1/battle start), Tote Bag (+2), Lucky Coin/Nana Berry/Shiny Berry (refund 1) extend the cap.'],
    ['Stat cap', '999,999,999 (0.7.4). Extended Mode runs to day 40 (0.7.2).'],
    ['Run length', '10 badges = championship. Batopedia stickers: Trophy (win), Medal (win at L3+), Star (win with Shiny).'],
  ],

  DATA_NOTE: 'Trainer & trinket percentages are REAL Master-Ranked data scraped from batodex.com (per-run pick rate, per-round win rate). Monster pick scores are a transparent heuristic model (DPS/status math + scaling + synergy + patch-informed adjustments) — Batodex publishes no monster win rates. Dataset generated ' + (window.BATODEX ? new Date(window.BATODEX.generatedAt).toLocaleDateString() : '') + ', patch 0.8.4 era.',
};
