/* Batomon Companion — i18n (EN/FR).
 * Game entities (Batomon, trainers, trinkets, items) stay in ENGLISH — the game is English.
 * Static long-form content (days/builds/mechanics) has full FR mirrors in guide.fr.js;
 * chrome + dynamic strings are translated here via exact-match + pattern dictionaries
 * applied to text nodes (MutationObserver keeps re-renders translated).
 */
window.LANG = (function () {
  let lang = localStorage.getItem('bc_lang') || 'en';

  const EXACT = {
    // nav
    '🎮 Live Run': '🎮 Partie live', 'Shop Advisor': 'Conseiller boutique', 'Live Synergies': 'Synergies live',
    'Trinket Picker': 'Choix de trinkets', 'Day-by-Day': 'Jour par jour', 'Tier Lists': 'Tier lists',
    'Builds': 'Builds', 'Batodex': 'Batodex', 'Mechanics': 'Mécaniques', 'Patches': 'Patchs',
    'Live Batodex data · Master Ranked win rates · patch 0.8.4 era': 'Données Batodex live · win rates Master · ère patch 0.8.4',
    // cockpit
    'Live Run': 'Partie live', '— mirror your game here; advice updates on every change': '— reflète ta partie ici ; les conseils se mettent à jour à chaque changement',
    'Day': 'Jour', 'Gold $': 'Or $', 'Lives': 'Vies', 'Badges': 'Badges', 'Trainer': 'Dresseur',
    '🔄 New run': '🔄 Nouvelle partie', '— pick your trainer —': '— choisis ton dresseur —',
    'Bottom row': 'Rangée du bas',
    'Trinkets you hold': 'Trinkets en ta possession', '+ Add trinket': '+ Ajouter un trinket',
    'None yet — add as you pick gifts.': 'Aucun — ajoute-les au fil des cadeaux.',
    'Current shop': 'Boutique actuelle', '+ Add what shop offers': '+ Ajouter les offres', 'Clear (reroll/new day)': 'Vider (reroll/nouveau jour)',
    'Empty — add the Batomon your shop is offering (mark shinies!).': 'Vide — ajoute les Batomon proposés (marque les shinies !).',
    '🛒 Buy advice': '🛒 Conseil d’achat', '· recalculates live on every board/shop/gold/trainer change': '· recalcule en direct à chaque changement de board/boutique/or/dresseur',
    'BEST PICK': 'MEILLEUR CHOIX', 'TAKE THIS': 'PRENDS ÇA',
    '📈 Closest measured comp on your board': '📈 Compo mesurée la plus proche de ton board',
    '💎 Trinket intel': '💎 Intel trinkets', 'Positioning moves': 'Placements',
    '🧮 Battle Brain': '🧮 Cerveau de combat', '📐 Positioning moves': '📐 Placements',
    'vs shop avg': 'vs moyenne boutique',
    // pickers
    'Pick a Batomon': 'Choisis un Batomon', 'Add shop offer': 'Ajouter une offre', 'Shop is offering…': 'La boutique propose…',
    'Add a trinket you hold': 'Ajouter un trinket possédé', 'Search…': 'Rechercher…', 'Search trinkets…': 'Rechercher un trinket…',
    'Level': 'Niveau', 'Shiny': 'Shiny', 'Clear slot': 'Vider la case',
    'Sort: Rarity ↑': 'Tri : Rareté ↑', 'Sort: Real WR ↓': 'Tri : WR réel ↓', 'Sort: Board synergy ↓': 'Tri : Synergie board ↓',
    'Sort: Cost ↓': 'Tri : Coût ↓', 'Sort: Name A-Z': 'Tri : Nom A-Z', 'Sort: Win rate ↓': 'Tri : Win rate ↓', 'Sort: Pick rate ↓': 'Tri : Pick rate ↓',
    // synergy tab
    'Best combos (2–6)': 'Meilleurs combos (2–6)', 'Monster meta (real WR)': 'Méta monstres (WR réel)',
    'Trainer combos': 'Combos dresseur', 'Trinket combos': 'Combos trinkets',
    'Combo size': 'Taille du combo', 'Phase': 'Phase', 'Min rounds': 'Manches min', 'Containing': 'Contenant',
    'All rounds': 'Toutes les manches', 'Early (day 1-3)': 'Début (j1-3)', 'Mid (day 4-6)': 'Milieu (j4-6)', 'Late (day 7+)': 'Fin (j7+)',
    'Pairs': 'Paires', 'Trios': 'Trios', 'Quads': 'Quatuors', 'Quints': 'Quintettes', 'Full boards (6)': 'Boards complets (6)',
    'Win rate': 'Win rate', 'Lift': 'Lift', 'Rounds': 'Manches', 'Runs': 'Runs', 'Trainer lift': 'Lift dresseur',
    'All days': 'Tous les jours', 'All rarities': 'Toutes raretés', 'All types': 'Tous types', 'All levels': 'Tous niveaux',
    'Level on board': 'Niveau sur board', 'Type': 'Type', 'Rarity': 'Rareté', 'All trainers': 'Tous les dresseurs',
    'monster name…': 'nom du monstre…', 'trinket or monster…': 'trinket ou monstre…',
    'Trinket pair (held together)': 'Paire de trinkets (portés ensemble)', 'Trinket trio (held together)': 'Trio de trinkets (portés ensemble)',
    'Batomon': 'Batomon', 'Trinket': 'Trinket', 'Trinkets': 'Trinkets',
    // tiers
    'Trainers (real WR)': 'Dresseurs (WR réel)', 'Trinkets (real WR)': 'Trinkets (WR réel)', 'Batomon (model)': 'Batomon (modèle)', 'Items (curated)': 'Objets (curaté)',
    'Early (day 1-3)': 'Début (j1-3)', 'Full table': 'Tableau complet', 'Ability': 'Capacité', 'Pick rate': 'Pick rate',
    // days tab
    'Day-by-Day Coach': 'Coach jour par jour',
    // dex
    'No shiny variant': 'Pas de variante shiny', 'Show shiny ✨': 'Voir shiny ✨', 'Show normal': 'Voir normal',
    'evolved form': 'forme évoluée', '✨ Shiny sprites': '✨ Sprites shiny',
    'Search name or type…': 'Nom ou type…',
    // news
    'Patches & Updates — live': 'Patchs & mises à jour — live', '↻ Reload feed': '↻ Recharger le flux',
    '⟳ Refresh ALL data (batomon + synergies)': '⟳ Rafraîchir TOUTES les données', '⟳ Refresh ALL data (batodex + synergies)': '⟳ Rafraîchir TOUTES les données',
    'Loading…': 'Chargement…',
    // hover card / hints
    'Click = change ·': 'Clic = changer ·', 'hover buttons: level / shiny / clear': 'boutons au survol : niveau / shiny / retirer',
    '× = remove': '× = retirer', 'Passive': 'Passif',
    '💡 Hover for stats & quick buttons ·': '💡 Survole pour stats & boutons ·', 'drag': 'glisse', 'to move/swap · drag out = remove': 'pour déplacer/échanger · glisser dehors = retirer',
    '+ add': '+ ajouter', '👑 carry': '👑 carry', '👑 carry slot': '👑 case carry',
    'no data': 'pas de données',
    // link cable
    // combo layouts
    '🧩 Combos (duos/trios/quads)': '🧩 Combos (duos/trios/quatuors)', '👤 Monsters': '👤 Monstres',
    'Duos': 'Duos', 'Quads': 'Quatuors',
    // multi-select + last life
    'Click monsters to stack them up (same one twice = duplicate offer), then confirm.': 'Clique les monstres pour les empiler (deux fois le même = offre en double), puis confirme.',
    '⚠️ LAST LIFE': '⚠️ DERNIÈRE VIE',
    // shop buying
    '+ Add items': '+ Ajouter des objets', 'Items on offer': 'Objets proposés',
    'Which items is the shop offering?': 'Quels objets la boutique propose-t-elle ?',
    'Search items…': 'Rechercher un objet…',
    '· click a chip = BUY · drag onto your board = buy into that slot': '· clic sur une puce = ACHETER · glisse sur ton board = acheter dans cette case',
    '🧾 Buy order': '🧾 Ordre d’achat',
    '· sequence-aware: free-first-bug, feeders before food, merges, budget': '· séquence optimisée : premier Bug gratuit, nourrisseurs avant leur nourriture, fusions, budget',
    'Add the items your shop offers — click one to BUY (gold + effects applied).': 'Ajoute les objets proposés — clique pour ACHETER (or + effets appliqués).',
    // bench
    '🪑 Bench': '🪑 Banc', '🪑 bench': '🪑 banc', 'bench': 'banc', 'bottom-right': 'bas-droite',
    '+5% CDS to the BOTTOM-RIGHT monster and refunds the use — position the right unit there first (target advice below)': '+5% CDS au monstre en BAS-DROITE et rend l’utilisation — place la bonne unité d’abord (conseil de cible en dessous)',
    '+8 Damage to the BOTTOM-RIGHT monster and refunds the use — position the right unit there first (target advice below)': '+8 Dégâts au monstre en BAS-DROITE et rend l’utilisation — place la bonne unité d’abord (conseil de cible en dessous)',
    'turns a RANDOM non-shiny monster shiny (+~20% stats, often an upgraded ability) — roll odds below': 'rend shiny un monstre non-shiny ALÉATOIRE (+~20% stats, souvent capacité améliorée) — probabilités en dessous',
    '(reserves — drag ⇄ board · merges & optimizer include it)': '(réserves — glisse ⇄ board · fusions & optimiseur inclus)',
    '(→ RIGHT = front / enemy side)': '(→ DROITE = front / côté ennemi)',
    '· click = BUY · drag onto board/bench = buy into that slot': '· clic = ACHETER · glisse sur board/banc = acheter dans cette case',
    'Need at least 2 units (board or bench).': 'Il faut au moins 2 unités (board ou banc).',
    '❌ Board & bench full — remove or merge a unit first.': '❌ Board & banc pleins — retire ou fusionne une unité d’abord.',
    // mulligan & reroll
    '🎰 Mulligan & reroll': '🎰 Mulligan & reroll',
    '🛡 KEEP SHOP': '🛡 GARDE LA BOUTIQUE', '🛒 BUY THEN REROLL': '🛒 ACHÈTE PUIS REROLL',
    '🔒 LOCK THE SHOP': '🔒 VERROUILLE LA BOUTIQUE',
    '🔒 LOCKED': '🔒 VERROUILLÉE', '🔓 Lock': '🔓 Verrouiller',
    'Team HP': 'PV équipe', '🧪 Item advice': '🧪 Conseil objets',
    '✓ BUY': '✓ ACHÈTE', '~ MAYBE': '~ PEUT-ÊTRE', '✗ SKIP': '✗ PASSE',
    'both teams share this base': 'les deux équipes partagent cette base',
    '≈ estimate — type the real bar to teach it': '≈ estimation — tape la vraie barre pour l’apprendre',
    'Pick your trainer above — portrait & passive show here.': 'Choisis ton dresseur au-dessus — portrait & passif apparaissent ici.',
    'Hits/s': 'Coups/s', '🛡 EHP': '🛡 EHP', 'Σ dmg': 'Σ dégâts', 'Σ team': 'Σ équipe',
    // batodex hub + game sync
    '👤 Batomon': '👤 Batomon', '🧪 Items': '🧪 Objets', '💎 Trinkets': '💎 Trinkets',
    '🧑 Trainers': '🧑 Dresseurs', '🎪 Events': '🎪 Événements',
    'Sort: Tier S→C': 'Tri : Tier S→C', 'Sort: Rarity ↑': 'Tri : Rareté ↑',
    '🔌 Game sync: OFF': '🔌 Sync jeu : OFF',
    '🧠 AI analysis': '🧠 Analyse IA', '🧠 Analyze': '🧠 Analyser',
    '📡 Community': '📡 Communauté', '📡 Community — live from the Steam forums': '📡 Communauté — en direct des forums Steam',
    // feedback tab
    '💬 Feedback': '💬 Feedback',
    'Found a bug? Wrong number? Feature idea? A build the advisor sleeps on? Tell me — every message lands straight in my inbox and my Discord. I read all of it.': 'Un bug ? Un chiffre faux ? Une idée de feature ? Un build que le conseiller sous-estime ? Dis-moi — chaque message arrive direct dans ma boîte mail et mon Discord. Je lis tout.',
    'Send me a message': 'Envoie-moi un message', 'Subject': 'Objet', 'Message': 'Message',
    'Your name': 'Ton nom', '(optional)': '(optionnel)',
    'How to reach you back': 'Comment te répondre', '(optional — email/Discord)': '(optionnel — email/Discord)',
    '📨 Send feedback': '📨 Envoyer', 'Or reach me directly': 'Ou contacte-moi directement',
    'Subject and message are both needed.': 'Il faut un objet ET un message.',
    '⏳ Sending…': '⏳ Envoi…',
    '🌐 Improve the stats for everyone': '🌐 Améliore les stats pour tout le monde',
    'Share my anonymized battle results': 'Partager mes résultats de combat anonymisés',
    'Collection opens at v1 — your choice is saved and takes effect the moment it goes live.': 'La collecte ouvre à la v1 — ton choix est sauvegardé et s’activera dès le lancement.',
    'Collection is LIVE — thank you for feeding the brain. 💙': 'La collecte est ACTIVE — merci de nourrir le cerveau. 💙',
    'Server offline — the choice is saved locally.': 'Serveur hors ligne — le choix est sauvegardé localement.',
    'With game sync on, your battles can contribute': 'Avec la sync jeu activée, tes combats peuvent contribuer des',
    'anonymized snapshots': 'instantanés anonymisés',
    '(board, result, trainer, trinkets — nothing personal) to the community dataset. Every run you play makes the win rates and advice sharper for the next player — and theirs for you.': '(board, résultat, dresseur, trinkets — rien de personnel) au dataset communautaire. Chaque run que tu joues affûte les win rates et les conseils pour le joueur suivant — et les siens pour toi.',
    ', benched,': ', sur le banc,',
    '✓ Sent — thank you! I read everything.': '✓ Envoyé — merci ! Je lis tout.',
    'Add me or DM me — happy to talk builds, bugs or the app.': 'Ajoute-moi ou envoie un DM — toujours partant pour parler builds, bugs ou de l’app.',
    '(username coming right up — meanwhile the form reaches my Discord too)': '(pseudo bientôt là — en attendant le formulaire arrive aussi sur mon Discord)',
    'I\'m active on the game\'s community spaces too — but this form is the fastest way to make the app better.': 'Je suis actif sur les espaces communautaires du jeu aussi — mais ce formulaire est le chemin le plus rapide pour améliorer l’app.',
    'copy': 'copier', '✓ copied': '✓ copié',
    '⚠️ The mailbox is finishing its one-time setup — try again in a bit, or email me directly below.': '⚠️ La boîte mail finit sa configuration initiale — réessaie dans un moment, ou écris-moi directement en dessous.',
    // who am i + coffee
    '🙋 Who am I': '🙋 Qui suis-je', '☕ Buy me a coffee': '☕ Offre-moi un café',
    'Hey — I\'m Julian 👋': 'Hey — moi c\'est Julian 👋',
    'Why I built this': 'Pourquoi j\'ai construit ça',
    'Support the project ☕': 'Soutenir le projet ☕',
    'Special thanks 💛': 'Remerciements 💛',
    'I\'m a builder. I spend my days shipping products, data pipelines and AI tools — and my evenings losing lives to autobattlers.': 'Je suis un builder. Je passe mes journées à shipper des produits, des pipelines de données et des outils IA — et mes soirées à perdre des vies dans des autobattlers.',
    'grabbed me instantly: simple to learn, deep to master, exactly the kind of game where a good decision beats a lucky roll.': 'm\'a happé direct : simple à apprendre, profond à maîtriser, exactement le genre de jeu où une bonne décision bat un tirage chanceux.',
    'This app is': 'Cette app est', 'free and fan-made': 'gratuite et fan-made',
    ', built for the love of the game. If it helped you win a badge (or ten), you can buy me a coffee — totally optional, and it would mean the world to me.': ', construite par amour du jeu. Si elle t\'a aidé à gagner un badge (ou dix), tu peux m\'offrir un café — totalement optionnel, et ça me toucherait énormément.',
    'for making this lovely game — and for letting fans build around it. Batomon Showdown is entirely their work: go': 'pour ce jeu adorable — et pour laisser les fans construire autour. Batomon Showdown est entièrement leur œuvre :',
    'wishlist & play it on Steam': 'wishlist & joue-y sur Steam',
    'and leave a review, that helps them way more than anything here.': 'et laisse un avis, ça les aide bien plus que tout ce qu\'il y a ici.',
    'Unofficial fan project — not affiliated with or endorsed by berrymint. All game assets, names and data belong to their creators; live database courtesy of batodex.com.': 'Projet de fan non officiel — ni affilié à, ni approuvé par berrymint. Tous les assets, noms et données appartiennent à leurs créateurs ; base de données live via batodex.com.',
    'I love playing': 'J’adore jouer à',
    '— and that\'s where I discovered that games get genuinely MORE fun when you learn them with a companion at your side (Path of Building, trade overlays… the game opens up instead of shrinking). I wanted that same': '— et c’est là que j’ai découvert qu’un jeu devient VRAIMENT plus fun quand on l’apprend avec un companion à ses côtés (Path of Building, overlays de trade… le jeu s’ouvre au lieu de rétrécir). Je voulais cette même',
    'Building it was': 'Le construire a été',
    'fun': 'fun',
    '— it genuinely made me happy and it challenged me. I hope the feeling is mutual when you play with it. 💙': '— ça m’a rendu sincèrement heureux et ça m’a challengé. J’espère que le sentiment sera réciproque quand tu joueras avec. 💙',
    'I wanted the': 'Je voulais l’', 'Mobalytics experience': 'expérience Mobalytics',
    'for Batomon: real numbers instead of gut feelings. So this companion reads the official': 'pour Batomon : des vrais chiffres plutôt que du feeling. Ce companion lit la base officielle',
    'database, crawls hundreds of top-Master runs for real win rates, simulates your battles with wiki-exact mechanics, and syncs with your live game in real time. Every single feature came from a real': ', crawle des centaines de runs top-Master pour des win rates réels, simule tes combats avec les mécaniques exactes du wiki, et se synchronise avec ta partie en temps réel. Chaque feature vient d’un vrai moment',
    '“I wish I knew this mid-run”': '« j’aurais aimé savoir ça en pleine run »',
    'moment.': '.',
    '🐛 Bugs & issues': '🐛 Bugs & problèmes', '📊 Meta & balance': '📊 Méta & équilibrage',
    'Filter threads…': 'Filtrer les fils…', '↻ Reload': '↻ Recharger', 'All': 'Tout',
    'Nothing matches — clear the filter or reload.': 'Aucun résultat — enlève le filtre ou recharge.',
    'Loading Steam discussions…': 'Chargement des discussions Steam…',
    'Public discussions for Batomon Showdown (main + demo apps): meta talk, bug reports, dev replies. Refreshes every 10 min — the 🧠 AI analysis reads the same feed. Official Discord isn\'t scrapable without ToS risk; this is the compliant pulse.': 'Discussions publiques de Batomon Showdown (app principale + démo) : méta, rapports de bugs, réponses des devs. Rafraîchi toutes les 10 min — l’🧠 Analyse IA lit le même flux. Le Discord officiel n’est pas scrapable sans risque ToS ; voici le pouls conforme.',
    'Ask a follow-up about this run… (optional)': 'Pose une question sur cette run… (optionnel)',
    '🧠 AI Battle Brain+': '🧠 AI Battle Brain+',
    '· live run + app advice + patch notes + Steam community → Claude': '· run live + conseils de l’app + patch notes + communauté Steam → Claude',
    'UNIQUE': 'UNIQUE', '1/round': '1/manche', 'starter pool': 'pool de départ',
    'In-battle scalers': 'Scalers en combat',
    '🎰 Shop:': '🎰 Boutique :', 'current best': 'meilleur actuel',
    'no gold to reroll ($1)': 'pas d’or pour un reroll ($1)',
    'Add what the shop offers to get a keep/reroll verdict.': 'Ajoute les offres de la boutique pour obtenir un verdict garder/reroll.',
    '✓ owned · 🛒 in this shop · 🎲 reroll target — packages are proven at top ranks IN this phase, rollable at your shop level, and affordable now.': '✓ possédé · 🛒 dans cette boutique · 🎲 cible de reroll — packages éprouvés aux rangs Master DANS cette phase, tirables à ton niveau de boutique et abordables maintenant.',
    // event applying
    '✓ Pick this': '✓ Prendre', '✓ Pick this → tell me what you rolled': '✓ Prendre → dis-moi ce que tu as tiré',
    'Which unit turned SHINY?': 'Quelle unité est devenue SHINY ?', 'Which unit leveled up?': 'Quelle unité a gagné un niveau ?',
    'No eligible unit on the board.': 'Aucune unité éligible sur le board.',
    'Computed from': 'Calculé sur',
    // positioning view
    'Positioning': 'Placements', 'Min placements': 'Placements min',
    'Each mini-board:': 'Chaque mini-board :',
    '% = how often top players place it there': '% = fréquence de placement chez les tops',
    'win rate in that slot': 'win rate dans cette case',
    '(WR colors). ⭐ = highest-WR slot (min 25 rounds). Crowd habit ≠ best slot — check both.': '(couleurs WR). ⭐ = case au meilleur WR (min 25 manches). Habitude ≠ meilleure case — regarde les deux.',
    '📐 Your layout is feeding these numbers:': '📐 Ton placement alimente ces chiffres :',
    '📊 Top players win most with': '📊 Les tops gagnent le plus avec',
    'Eight proven engine shapes assembled from current abilities (patch 0.8.4 roster) and real trainer win rates. Click a build for the full plan.': 'Des moteurs éprouvés assemblés depuis les capacités actuelles (roster 0.8.4) et les win rates réels des dresseurs. Clique un build pour le plan complet.',
    // comp plan + second chance + breakdown
    '🕊 Second Chance (lives → 1)': '🕊 Second Chance (vies → 1)',
    '🎯 Set as run plan': '🎯 Définir comme plan de run', '🎯 Set as run plan ✓ (active)': '🎯 Plan actif ✓',
    '🎯 Composition plan': '🎯 Plan de composition', '✕ drop plan': '✕ abandonner',
    'Core': 'Noyau', 'Late game': 'Fin de partie', 'Trinkets to grab': 'Trinkets à prendre',
    '✓ All comp pieces on board!': '✓ Toutes les pièces de la compo sont là !',
    'Casts': 'Casts', 'Unit': 'Unité',
    // events + shop odds + income
    '🎪 Event advisor': '🎪 Conseiller d’événements', '+ Add event': '+ Ajouter un événement',
    'Which event did you hit?': 'Quel événement as-tu croisé ?', 'PICK THIS': 'PRENDS ÇA',
    '+ Add to board': '+ Ajouter au board', '← All events': '← Tous les événements',
    'Board full — clear a slot first': 'Board plein — libère une case',
    'Hit an event in-game? Pick it — every choice gets scored for YOUR board with real values.': 'Un événement en jeu ? Choisis-le — chaque option est notée pour TON board avec les vraies valeurs.',
    'Shop Lv': 'Niv. boutique', 'Next income': 'Prochain revenu',
    // run flow + optimizer
    '✓ Victory': '✓ Victoire', '✗ Defeat': '✗ Défaite', 'Income/day': 'Revenu/jour',
    '📜 Run history': '📜 Historique de la run', '✓ WIN': '✓ GAGNÉ', '✗ LOSS': '✗ PERDU',
    '🧲 Optimize positioning': '🧲 Optimiser le placement',
    '✓ Already optimal for the expected battle.': '✓ Déjà optimal pour le combat attendu.',
    'Need at least 2 units on board.': 'Il faut au moins 2 unités sur le board.',
    '🏆 ': '🏆 ', 'CHAMPION — 10 badges!': 'CHAMPION — 10 badges !',
    ' Extended Mode continues to day 40.': ' Le mode Extended continue jusqu’au jour 40.',
    'Run over — 0 lives.': 'Run terminée — 0 vie.', ' Hit 🔄 New run.': ' Clique 🔄 Nouvelle partie.',
    // misc
    'Run context': 'Contexte de partie', 'Trainer (real win rates)': 'Dresseur (win rates réels)',
    'Advise me ➜': 'Conseille-moi ➜', '+ Add offer': '+ Ajouter une offre', 'Clear': 'Vider',
    'Shop offers this round': 'Offres de la boutique', 'Your gift options': 'Tes options de cadeau',
    'Add at least one shop offer first.': 'Ajoute d’abord au moins une offre.',
    'Add at least one shop offer or item first.': 'Ajoute d’abord au moins une offre ou un objet.',
    '🔌 Mirror live run': '🔌 Copier la run live', '🆕 New sandbox': '🆕 Nouveau bac à sable',
    '(counts for merges & item rolls)': '(compte pour les fusions & tirages d’objets)',
    '💎 Trinkets held': '💎 Trinkets portés', '(rarity odds + real-data pairing)': '(probas de rareté + paires réelles)',
    'None — odds use the base table.': 'Aucun — les probas utilisent la table de base.',
    '🎒 Items held': '🎒 Objets en main', '(unused — Coupon discounts every pick)': '(non utilisés — le Coupon réduit chaque achat)',
    '🎁 Gift choice': '🎁 Choix de cadeau', '🎁 Gift choice — which trinket to take?': '🎁 Choix de cadeau — quel trinket prendre ?',
    'Click the trinkets the game is offering (2–4), then compare — scored against YOUR board, trainer and held trinkets.': 'Clique les trinkets que le jeu propose (2–4), puis compare — notés contre TON board, ton dresseur et tes trinkets.',
    'Add at least 2 options to compare.': 'Ajoute au moins 2 options à comparer.',
    '✓ took it': '✓ pris',
    'TAKE THIS': 'PRENDS ÇA',
    '· sequence-aware: economy items first, free-first-bug, feeders before food, merges, space, budget': '· séquence optimisée : objets éco d’abord, premier Bug gratuit, nourrisseurs avant leur nourriture, fusions, place, budget',
    '+ Add held item': '+ Ajouter un objet en main',
    'None — add items you\'re sitting on.': 'Aucun — ajoute les objets que tu gardes.',
    '✓ USE NOW': '✓ UTILISE', '~ HOLD OR USE': '~ GARDE OU UTILISE', '✗ HOLD': '✗ GARDE',
    '🎒 HELD': '🎒 EN MAIN',
    '· scored for THIS sandbox board · held items get use-now/hold timing': '· noté pour CE board bac à sable · les objets en main reçoivent un timing utilise/garde',
    '· scored for THIS sandbox board': '· noté pour CE board bac à sable',
    'Add the items on offer — each gets a BUY/SKIP verdict + roll odds in the results.': 'Ajoute les objets proposés — chacun reçoit un verdict ACHÈTE/PASSE + les probabilités de tirage dans les résultats.',
    'Mechanics Cheat Sheet': 'Antisèche des mécaniques',
  };

  const PATTERNS = [
    // engine chips
    [/^Real Master data: ([\d.]+)% round WR · ([\d.]+)% of top runs \(([\d,  ]+) rounds?\)$/, 'Données Master réelles : $1% WR/manche · $2% des runs top ($3 manches)'],
    [/^Proven pair with (.+?): ([\d.]+)% WR \(([+\-][\d.]+)pp lift, (\d+) rounds?\)$/, 'Paire éprouvée avec $1 : $2% WR (lift $3pp, $4 manches)'],
    [/^Completes a proven (\d)-combo with (.+?): ([\d.]+)% WR \((\d+) rounds?\)$/, 'Complète un combo à $1 éprouvé avec $2 : $3% WR ($4 manches)'],
    [/^Completes EVOLUTION → (.+?) at Level (\d)$/, 'Déclenche l’ÉVOLUTION → $1 au niveau $2'],
    [/^2nd copy — spare body \(1 more 3-merges to Level 2\)$/, '2e copie — corps en réserve (1 de plus fusionne au niveau 2)'],
    [/^3rd copy → 3-merges to Level 2 now$/, '3e copie → fusion au niveau 2 maintenant'],
    [/^Completes Level 3 \(9 copies\)$/, 'Complète le niveau 3 (9 copies)'],
    [/^(\d+) copies → Level (\d)$/, '$1 copies → niveau $2'],
    [/^SHINY: ~\+20% stats( \+ upgraded ability)? \+ Batopedia Star$/, 'SHINY : ~+20% stats$1 + étoile Batopedia'],
    [/^ \+ upgraded ability$/, ' + capacité améliorée'],
    [/^Victory evolution line \(→ (.+)\)$/, 'Ligne d’évolution par victoire (→ $1)'],
    [/^Cannot afford \(\$(\d+) > \$(\d+)\)$/, 'Pas les moyens ($$$1 > $$$2)'],
    [/^FREE — first Bug this round \(\$(\d+) → \$0, Bug Catcher\)$/, 'GRATUIT — premier Bug de la manche ($$$1 → $0, Bug Catcher)'],
    [/^Ranger target — free copy every 2 days keeps this merging$/, 'Cible du Ranger — copie gratuite tous les 2 jours, fusions assurées'],
    [/^Your (.+?) \+ this pick: ([\d.]+)% WR \(([+\-][\d.]+)pp, (\d+) rounds?\)$/, 'Ton $1 + ce choix : $2% WR ($3pp, $4 manches)'],
    [/^With (.+?) at top ranks: ([\d.]+)% WR \((\d+) rounds?\)$/, 'Avec $1 au top classement : $2% WR ($3 manches)'],
    [/^(.+?) \+ (.+?): ([\d.]+)% WR \(([+\-][\d.]+)pp trainer lift, (\d+) rounds?\)$/, '$1 + $2 : $3% WR (lift dresseur $4pp, $5 manches)'],
    [/^Type stack: (.+)$/, 'Stack de type : $1'],
    [/^Chef cooks it Fire \(single-typed\)$/, 'Le Chef le passe Feu (mono-type)'],
    [/^Chef synergy \(fire\)$/, 'Synergie Chef (feu)'],
    [/^Musician: your ONE Electric carry \(\+150% Shock\)$/, 'Musician : ton UNIQUE carry Électrik (+150% Shock)'],
    [/^Musician wants EXACTLY 1 Electric — this breaks the bonus$/, 'Musician veut EXACTEMENT 1 Électrik — ceci casse le bonus'],
    [/^Burn package deepens$/, 'Le package Brûlure s’approfondit'],
    [/^Poison package deepens$/, 'Le package Poison s’approfondit'],
    [/^Shock amplifies your fast attackers$/, 'Le Shock amplifie tes attaquants rapides'],
    [/^Charges your Electric units$/, 'Charge tes unités Électrik'],
    [/^Trigger chain has targets$/, 'La chaîne de triggers a des cibles'],
    [/^Item engine online$/, 'Moteur à objets en ligne'],
    // reroll notes
    [/^Strong shop — buy the top pick before rerolling anything\.$/, 'Boutique forte — achète le meilleur choix avant tout reroll.'],
    [/^Weak shop for day (\d+) — reroll if you have free rerolls or spare gold\.$/, 'Boutique faible pour le jour $1 — reroll si tu as des rerolls gratuits ou de l’or en rab.'],
    // battle brain fragments
    [/^Expected battle:$/, 'Combat attendu :'],
    [/^ · you break them in ~(\d+)s, they break you in ~(\d+)s → $/, ' · tu les brises en ~$1s, ils te brisent en ~$2s → '],
    [/^FAVORED$/, 'FAVORI'], [/^CLOSE$/, 'SERRÉ'], [/^BEHIND$/, 'EN RETARD'],
    [/^\(([+\-]\d+)% margin\)$/, '(marge $1%)'],
    [/^You$/, 'Toi'], [/^Avg day-(\d+) enemy$/, 'Ennemi moyen j$1'],
    [/^Direct DPS$/, 'DPS direct'], [/^Heal\/s$/, 'Soin/s'], [/^Shield\/s$/, 'Bouclier/s'], [/^Burn\/s$/, 'Brûlure/s'], [/^Poison\/s$/, 'Poison/s'], [/^Shock\/s$/, 'Shock/s'],
    [/^model \+ real day-(\d+) enemy averages \((\d+) top-rank boards\)$/, 'modèle + moyennes réelles des ennemis j$1 ($2 boards du top)'],
    [/^☠️ Your poison alone out-damages their sustain from ~(\d+)s — (.*)$/, '☠️ Ton poison seul dépasse leur sustain dès ~$1s — $2'],
    [/^the ramp pays off in this fight length ✓$/, 'la montée paie sur cette durée de combat ✓'],
    // greed
    [/^🟢 $/, '🟢 '], [/^Greed window OPEN$/, 'Fenêtre de GREED OUVERTE'], [/^STOP GREEDING$/, 'STOP AU GREED'], [/^Even matchup$/, 'Duel équilibré'],
    // positioning fragments
    [/^put (.+?) directly to the LEFT of (.+?) \(behind it, same row\)\. $/, 'place $1 directement à GAUCHE de $2 (derrière lui, même rangée).'],
    [/^put (.+?) directly to the RIGHT of (.+?) \(in front of it, same row\)\. $/, 'place $1 directement à DROITE de $2 (devant lui, même rangée).'],
    [/^(.+?) in the BOTTOM row, (.+?) directly ABOVE it \(same column\)\. $/, '$1 sur la rangée du BAS, $2 juste AU-DESSUS (même colonne).'],
    [/^keep (.+?) touching (.+?) \(middle slots maximize neighbours\)\. $/, 'garde $1 au contact de $2 (les cases centrales maximisent les voisins).'],
    [/^already positioned\. $/, 'déjà bien placé.'],
    [/^≈ \+(\d+)% CDS by fight end \(avg \+(\d+)%\) → ~\+([\d.]+) DPS$/, '≈ +$1% de vitesse de recharge en fin de combat (moy. +$2%) → ~+$3 DPS'],
    [/^≈ ([\d.]+) extra casts → ~\+(\d+) damage this fight$/, '≈ $1 casts en plus → ~+$2 dégâts ce combat'],
    [/^≈ (\d+) bonus casts of (.+?) → ~\+(\d+) damage$/, '≈ $1 casts bonus de $2 → ~+$3 dégâts'],
    [/^≈ \+(\d+) Poison stacks → ~\+(\d+) damage over the fight \(ramps\)$/, '≈ +$1 stacks de Poison → ~+$2 dégâts sur le combat (montée)'],
    [/^≈ \+(\d+) Burn by fight end$/, '≈ +$1 Brûlure en fin de combat'],
    [/^doubles (.+?)'s Shock output$/, 'double le Shock de $1'],
    [/^ ⚠️ (.+?) is near the 1s cooldown floor — CDS is nearly wasted, stop greeding it here\.$/, ' ⚠️ $1 est proche du plancher de recharge (1s) — la vitesse est quasi gâchée, arrête de greed ici.'],
    // arrows tooltips
    [/^(.*) — no slot that way$/, '$1 — pas de case dans cette direction'],
    [/^(.*) — pointing at an empty slot$/, '$1 — pointe vers une case vide'],
    [/^(.*) — target doesn't match \(needs (.+)\)$/, '$1 — la cible ne correspond pas (requiert $2)'],
    // trainer panel bits (dynamic)
    [/^🧠 (.+) logic — live$/, '🧠 Logique $1 — live'],
    [/^Free copies so far:$/, 'Copies gratuites reçues :'],
    [/^ \(next lands $/, ' (la prochaine arrive '],
    [/^day (\d+)$/, 'jour $1'],
    [/^Bug bought this round\? $/, 'Bug acheté cette manche ? '],
    [/^Level-ups this run$/, 'Montées de niveau cette partie'], [/^Victories so far$/, 'Victoires jusqu’ici'],
    [/^Mask currently copies$/, 'Le masque copie actuellement'], [/^— none yet —$/, '— aucun —'],
    [/^📅 Day (\d+) plan — (.*)$/, '📅 Plan du jour $1 — $2'],
    [/^DAY (\d+)$/, 'JOUR $1'],
    [/^Your board — top row$/, 'Ton board — rangée du haut'],
    [/^\(→ RIGHT column = front \/ enemy side, LEFT = back\)$/, '(→ colonne DROITE = front / côté ennemi, GAUCHE = arrière)'],
    // mulligan & reroll card
    [/^🎲 REROLL \(\$(\d+)\)$/, '🎲 REROLL ($$$1)'],
    [/^· exact rarity odds \(Shop Lv (\d+)\) × engine scores vs your board$/, '· probabilités de rareté exactes (Niv. boutique $1) × scores moteur vs ton board'],
    [/^Best early-game packages to assemble today \(day (\d+), \$(\d+)\)$/, 'Meilleurs packages début de partie à assembler aujourd’hui (jour $1, $$$2)'],
    [/^Best mid-game packages to assemble today \(day (\d+), \$(\d+)\)$/, 'Meilleurs packages milieu de partie à assembler aujourd’hui (jour $1, $$$2)'],
    [/^Best late-game packages to assemble today \(day (\d+), \$(\d+)\)$/, 'Meilleurs packages fin de partie à assembler aujourd’hui (jour $1, $$$2)'],
    [/^\$(\d+) to finish$/, '$$$1 pour finir'],
    [/^\((\d+) rds\)$/, '($1 manches)'],
    [/^(early|mid|late) WR$/, 'WR $1'],
    [/^Bench (\d)$/, 'Banc $1'],
    // generic
    [/^(\d+) combos · lift = vs same Batomon combo under ANY trainer$/, '$1 combos · lift = vs le même combo sous N’IMPORTE quel dresseur'],
    [/^(\d+) combos · lift = what holding the trinket adds to that board$/, '$1 combos · lift = ce que le trinket apporte à ce board'],
    [/^(\d+) combos · lift = vs each trinket held alone$/, '$1 combos · lift = vs chaque trinket porté seul'],
    [/^(\d+) combos$/, '$1 combos'],
    [/^(\d+) monsters · min 20 rounds in slice( · level overrides day)?$/, '$1 monstres · min 20 manches dans la tranche$2'],
    [/^ · level overrides day$/, ' · le niveau prime sur le jour'],
    [/^Day (\d+)\+?$/, 'Jour $1'],
    [/^open ↗$/, 'ouvrir ↗'],
    [/^🔗 Link Cable makes everyone adjacent — (S+)'s aura hits the whole board, position it freely$/, '🔗 Link Cable rend tout le monde adjacent — l’aura de $1 touche tout le board, place-le librement'],
    [/ — 🔗 Link Cable: ALL allies count as adjacent/g, ' — 🔗 Link Cable : TOUS les alliés comptent comme adjacents'],
    [/^✓ Add (d+) offers?$/, '✓ Ajouter $1 offre(s)'],
    [/^🕊 SECOND CHANCE — win or it's over$/, '🕊 SECOND CHANCE — gagne ou c’est fini'],
    [/^Day (d+)$/, 'Jour $1'],
    [/^✓ Rearranged: $/, '✓ Réarrangé : '],
    [/^ estimated battle output (DPS + CDS donors + triggers + adjacency, vs expected fight length).$/, ' de rendement de combat estimé (DPS + donneurs de vitesse + triggers + adjacence, vs durée attendue).'],
  ];

  // Unanchored patterns applied ANYWHERE inside long composite text nodes
  // (Battle Brain sentences, trainer panels, greed meter — built with variables).
  const PATTERNS_INLINE = [
    // ⚔️ win probability + 🧭 run health + 🎲 hit odds + 📊 run graph + day notes
    [/~(\d+)% win chance/g, '~$1% de chances de gagner'],
    [/(\d+)% coin-flip close\)/g, '$1% pile-ou-face)'],
    [/🧭 ON TRACK/g, '🧭 SUR LA VOIE'], [/🧭 AT RISK/g, '🧭 À RISQUE'], [/🧭 CRITICAL/g, '🧭 CRITIQUE'],
    [/healthy life buffer/g, 'bonne réserve de vies'], [/thin life buffer/g, 'réserve de vies mince'], [/LAST LIFE — must win/g, 'DERNIÈRE VIE — victoire obligatoire'],
    [/favored today/g, 'favori aujourd’hui'], [/close fight today/g, 'combat serré aujourd’hui'], [/behind today — fix the board/g, 'en retard aujourd’hui — corrige le board'],
    [/champion pace/g, 'rythme de champion'], [/slightly off champion pace/g, 'léger retard sur le rythme champion'], [/well off champion pace — need win streaks/g, 'gros retard sur le rythme champion — il faut enchaîner les victoires'],
    [/🎲 ~\$(\d+) for 80%/g, '🎲 ~$$$1 pour 80%'],
    [/not in Shop Lv (\d+) pool/g, 'absent du pool Boutique Nv $1'],
    [/This rarity can't roll at Shop Lv (\d+) — raise shop level first/g, 'Cette rareté ne peut pas apparaître au Nv $1 de boutique — monte le niveau d’abord'],
    [/\(pool-blind estimate\)/g, '(estimation sans épuisement du pool)'],
    [/— gold<\/span>/g, '— or</span>'], [/— lives<\/span>/g, '— vies</span>'], [/— badges<\/span>/g, '— badges</span>'],
    [/day (\d+)→(\d+) \(each line scaled to its own max\)/g, 'jour $1→$2 (chaque courbe à sa propre échelle)'],
    [/💰 lost with \$(\d+) banked — over-saving\? Gold you don't spend can't fight/g, '💰 défaite avec $$$1 en banque — trop économe ? L’or non dépensé ne se bat pas'],
    [/⚠️ lives bleeding early — stabilize the board before greeding/g, '⚠️ vies qui fondent tôt — stabilise le board avant de greed'],
    [/♟️ no strategy adopted this run — commit to an engine earlier/g, '♟️ aucune stratégie adoptée cette partie — engage-toi sur un moteur plus tôt'],
    [/🎲 what finding it should cost/g, '🎲 coût estimé pour le trouver'],
    // 📈 profile tab — 🎖 ranked
    [/🎖 Ranked/g, '🎖 Classé'],
    [/synced from the game's run save ✓/g, 'synchronisé depuis la sauvegarde du jeu ✓'],
    [/manual — the run save doesn't expose rank \(it lives in the encrypted meta save\); auto-syncs the day it appears/g, 'manuel — la sauvegarde de run n’expose pas le rang (il vit dans la sauvegarde méta chiffrée) ; auto-sync dès qu’il apparaît'],
    [/The run save doesn't expose your rank\/MMR \(that's in the game's encrypted meta save — asked berrymint to surface it\)\. Enter what the ranked screen shows:/g, 'La sauvegarde de run n’expose pas ton rang/MMR (c’est dans la sauvegarde méta chiffrée — demandé à berrymint). Entre ce que montre l’écran classé :'],
    [/opponents avg ~(\d+) MMR \((\d+) sampled( via battle-sync)?\)/g, 'adversaires ~$1 MMR en moyenne ($2 échantillonnés$3)'],
    [/✎ update/g, '✎ modifier'],
    // 📈 profile tab
    [/📈 Profile/g, '📈 Profil'],
    [/— built from your (\d+) archived runs?, all local/g, '— construit depuis tes $1 parties archivées, tout en local'],
    [/Your player page builds itself from finished runs[^.]*\./g, 'Ta page joueur se construit depuis tes parties terminées — joue avec 🔌 Sync et reviens.'],
    [/Skill radar/g, 'Radar de compétences'], [/Per-trainer record/g, 'Bilan par dresseur'],
    [/🎯 <b>Work on (\w+)<\/b>/g, '🎯 <b>Travaille $1</b>'],
    [/>Championships</g, '>Championnats<'], [/>Brain calls</g, '>Prédictions<'], [/>Followed #1</g, '>Suivi du n°1<'],
    [/Form:/g, 'Forme :'], [/ main</g, ' main<'],
    [/Tier anchors: CHAMPION = a 10-badge run · CONTENDER = 7\+ · CHALLENGER = 4\+ · GRANDMASTER = 3 championships\. Population-relative ranking arrives with community data at v1\./g, 'Paliers : CHAMPION = partie à 10 badges · CONTENDER = 7+ · CHALLENGER = 4+ · GRANDMASTER = 3 championnats. Le classement relatif à la population arrive avec les données communautaires en v1.'],
    [/win earlier: prioritize tempo buys days 1–3 \(the 🎰 verdict \+ ⚔️ chips\) instead of saving/g, 'gagne plus tôt : priorise les achats tempo jours 1–3 (verdict 🎰 + puces ⚔️) au lieu d’économiser'],
    [/your boards lose fights — lean on 🧲 sim-verified positioning and the 🧭 buy plan before greeding/g, 'tes boards perdent leurs combats — appuie-toi sur le placement 🧲 vérifié par sim et le plan 🧭 avant de greed'],
    [/gold sitting idle on loss days — spend into the board when the Brain says BEHIND; income comes back, lives don't/g, 'de l’or qui dort les jours de défaite — investis dans le board quand le Cerveau dit EN RETARD ; l’or revient, pas les vies'],
    [/adopt a ♟️ strategy earlier \(day 4–6\) — committed runs average more badges/g, 'adopte une stratégie ♟️ plus tôt (jour 4–6) — les parties engagées font plus de badges en moyenne'],
    [/try following the brain's #1 pick more often — the 🧠 decision grades will show if it pays/g, 'essaie de suivre plus souvent le choix n°1 du cerveau — les notes 🧠 diront si ça paie'],
    // batch F1-F8 + I2-I5
    [/↕ Opponent model scaled <b>\+(\d+)%<\/b> — you're on a (\d+)-loss streak and matchmaking pairs records \(calibration-proven on your own runs\)\./g, '↕ Modèle adverse relevé de <b>+$1%</b> — tu es sur une série de $2 défaites et le matchmaking apparie les scores (prouvé par calibration sur tes parties).'],
    [/🏁 <b>Champion path<\/b>: (\d+) more wins?/g, '🏁 <b>Route du champion</b> : encore $1 victoire(s)'],
    [/the math closes — hold this pace/g, 'le calcul passe — garde ce rythme'],
    [/the math does NOT close — you need a stronger board \(raise WR\) before the lives run out/g, 'le calcul ne passe PAS — il faut un board plus fort (monter le WR) avant d’épuiser les vies'],
    [/📦 Export data/g, '📦 Exporter les données'], [/📥 Import a backup/g, '📥 Importer une sauvegarde'], [/📥 Import/g, '📥 Importer'],
    [/🔗 Share this board/g, '🔗 Partager ce board'], [/📋 Copy code/g, '📋 Copier le code'], [/🔗 Copy link/g, '🔗 Copier le lien'],
    [/⤵ Load into Live Run/g, '⤵ Charger dans la partie'], [/🔗 Shared board/g, '🔗 Board partagé'],
    [/🧑✨ Who should I pick\?/g, '🧑✨ Qui choisir ?'],
    [/📋 Dataset changes on last refresh/g, '📋 Changements du dataset au dernier refresh'],
    [/\(community-blended rate\)/g, '(taux mixé communauté)'],
    [/Skip tour/g, 'Passer'], [/Next →/g, 'Suivant →'], [/Done ✓/g, 'Terminé ✓'],
    // ⚔️ Δwin chips + 🏆 gallery + 📤 card + 🗖 overlay + 🔔 notifs + 📼 live calib
    [/⚔️ \+(\d+)% win/g, '⚔️ +$1% victoire'], [/⚔️ -(\d+)% win/g, '⚔️ −$1% victoire'], [/⚔️ \+0% win/g, '⚔️ +0% victoire'],
    [/🏆 Real winning boards — day (\d+)/g, '🏆 Vrais boards gagnants — jour $1'],
    [/· top-MMR Master rounds that WON this day/g, '· manches Master haut-MMR GAGNANTES ce jour'],
    [/steal shapes, not just units\./g, 'pique les FORMES, pas juste les unités.'],
    [/📤 Summary card/g, '📤 Carte résumé'], [/📤 Run summary card/g, '📤 Carte résumé de partie'],
    [/⬇ Download PNG/g, '⬇ Télécharger PNG'], [/📋 Copy image/g, '📋 Copier l’image'],
    [/🗖 Overlay/g, '🗖 Superposition'],
    [/📼 <b>Live-model calibration<\/b> \(predictions made in real time, full state\): <b>(\d+)\/(\d+)<\/b> called · Brier ([\d.]+) — this is the number that matters as it accumulates\./g, '📼 <b>Calibration du modèle live</b> (prédictions en temps réel, état complet) : <b>$1/$2</b> prédits · Brier $3 — c’est LE chiffre qui compte à mesure qu’il s’accumule.'],
    [/📐 sim noise fitted on (\d+) battles/g, '📐 bruit de sim ajusté sur $1 combats'],
    [/📐 sim noise: defaults \(fits itself at 3\+ runs \/ 25\+ battles\)/g, '📐 bruit de sim : défauts (s’ajuste à 3+ parties / 25+ combats)'],
    [/🧪 bought item ([A-Za-z' ]+) — advice said ([A-Z]+)/g, '🧪 item acheté $1 — le conseil disait $2'],
    [/· against advice/g, '· contre le conseil'],
    [/💰 sold ([A-Za-z' ]+)/g, '💰 a vendu $1'], [/✓ the recommended cut/g, '✓ la coupe recommandée'],
    [/⚠️ was PROTECTED \(plan\/engine piece\)/g, '⚠️ était PROTÉGÉ (pièce de plan/moteur)'],
    // 🎯 calibration + 🧠 decisions + 🎲 pool tracking + ⚖️ divergence
    [/🎯 <b>Brain calibration<\/b>: the event sim would have called <b>(\d+)\/(\d+)<\/b> of this run's battles \(Brier ([\d.]+), lower is better\) — replayed vs day-average enemies, final trinkets, positions approximated\./g, '🎯 <b>Calibration du cerveau</b> : la sim événementielle aurait prédit <b>$1/$2</b> combats de cette partie (Brier $3, plus bas = mieux) — rejoués contre les ennemis moyens du jour, trinkets finaux, positions approximées.'],
    [/Takeaway: your real opponents ran stronger than the day-average/g, 'À retenir : tes vrais adversaires étaient plus forts que la moyenne du jour'],
    [/ — matchmaking pairs records, so on a losing streak treat FAVORED verdicts with caution\./g, ' — le matchmaking apparie les scores : en série de défaites, prends les verdicts FAVORI avec prudence.'],
    [/🧠 <b>Decisions<\/b>: followed the brain's #1 pick in <b>(\d+)\/(\d+)<\/b> tracked buys/g, '🧠 <b>Décisions</b> : a suivi le choix n°1 du cerveau sur <b>$1/$2</b> achats suivis'],
    [/big divergences? \(≥30% below the top pick\)/g, 'grosses divergences (≥30% sous le meilleur choix)'],
    [/ — per-day detail in the timeline below\./g, ' — détail par jour dans la chronologie ci-dessous.'],
    [/bought ([A-Za-z' ]+) — brain rank #(\d+) \((\d+)%\)/g, 'a acheté $1 — rang cerveau n°$2 ($3%)'],
    [/✓ top pick/g, '✓ meilleur choix'], [/(\d+)% below the top pick/g, '$1% sous le meilleur choix'],
    [/rerolled — brain said ([A-Z]+)/g, 'reroll — le cerveau disait $1'], [/✓ aligned/g, '✓ aligné'],
    [/· seen (\d+)×\/(\d+) shops this run/g, '· vu $1×/$2 boutiques cette partie'],
    [/ — running COLD vs expectation/g, ' — FROID vs l’attendu'], [/· cold/g, '· froid'],
    [/⚖️ <b>Models disagree<\/b>/g, '⚖️ <b>Les modèles divergent</b>'],
    [/but the integral model says /g, 'mais le modèle intégral dit '],
    [/— trusting the event sim \(discrete casts, real burn decay\); treat the verdict with extra care this round\./g, '— on suit la sim événementielle (casts discrets, vraie décroissance du burn) ; prends le verdict avec des pincettes ce tour.'],
    [/event timeline says /g, 'la chronologie événementielle dit '],
    [/📅 <b>Power spike TOMORROW<\/b>/g, '📅 <b>Pic de puissance DEMAIN</b>'],
    [/📅 <b>Power spike day (\d+)<\/b>/g, '📅 <b>Pic de puissance jour $1</b>'],
    [/: enemy HP jumps /g, ' : les PV ennemis bondissent de '],
    [/ — tomorrow is \+(\d+)%/g, ' — demain c’est +$1%'],
    [/Get your merges\/evolutions online <b>before<\/b> it/g, 'Mets tes fusions/évolutions en ligne <b>avant</b>'],
    [/, and don’t greed into it with a close board/g, ', et ne greed pas dedans avec un board serré'],
    // 🏆 Game History tab
    [/🏆 Game History/g, '🏆 Historique des parties'], [/📜 This run — battle log/g, '📜 Cette partie — journal de combats'],
    [/— (\d+) runs? recorded · click a run to expand/g, '— $1 parties enregistrées · clique pour développer'],
    [/🏆 Game History — (\d+) past runs? ›/g, '🏆 Historique — $1 parties passées ›'],
    [/No runs recorded yet\..*breakdown\./g, 'Aucune partie enregistrée pour l’instant. Joue avec 🔌 Sync activé (ou pilote le cockpit à la main) — chaque partie terminée est archivée ici automatiquement avec son détail jour par jour.'],
    [/Most-played trainer:/g, 'Dresseur le plus joué :'], [/Favorite strategy:/g, 'Stratégie favorite :'],
    [/RUN COMPLETE — Champion!/g, 'PARTIE GAGNÉE — Champion !'], [/🏆 View history/g, '🏆 Voir l’historique'],
    [/>Runs</g, '>Parties<'], [/>Champions 🏆</g, '>Champions 🏆<'], [/>Best badges</g, '>Meilleurs badges<'],
    [/>Avg badges</g, '>Badges moy.<'], [/>Avg day</g, '>Jour moy.<'], [/>Battle win-rate</g, '>Taux victoire<'],
    [/>BADGES</g, '>BADGES<'], [/>DAY REACHED</g, '>JOUR ATTEINT<'], [/>WINS</g, '>VICTOIRES<'], [/>LOSSES</g, '>DÉFAITES<'], [/>PEAK GOLD</g, '>OR MAX<'], [/>INCOME</g, '>REVENU<'],
    [/<b>Final board:<\/b>/g, '<b>Board final :</b>'], [/<b>💎 Trinkets:<\/b>/g, '<b>💎 Trinkets :</b>'], [/<b>♟️ Strategy:<\/b>/g, '<b>♟️ Stratégie :</b>'], [/<b>🎯 Plan:<\/b>/g, '<b>🎯 Plan :</b>'],
    [/· (\d+) past runs? — click one for the full breakdown/g, '· $1 parties passées — clique pour le détail complet'],
    [/💀 RUN ENDED — 0 lives\./g, '💀 PARTIE TERMINÉE — 0 vie.'],
    [/Reached <b>day (\d+)<\/b> · <b>(\d+)<\/b> 🏅/g, 'Atteint <b>jour $1</b> · <b>$2</b> 🏅'],
    [/\. Saved to 🏆 Game History below\./g, '. Sauvegardé dans 🏆 Historique des parties ci-dessous.'],
    [/🔄 Start new run/g, '🔄 Nouvelle partie'],
    [/📅 Day-by-day — battles, strategies &amp; choices/g, '📅 Jour par jour — combats, stratégies & choix'],
    [/No per-day detail was recorded for this run\./g, 'Aucun détail par jour enregistré pour cette partie.'],
    [/🏆 CHAMPION/g, '🏆 CHAMPION'], [/💀 DIED/g, '💀 MORT'], [/↩ ABANDONED/g, '↩ ABANDONNÉE'], [/⏹ ENDED/g, '⏹ TERMINÉE'],
    [/every monster → \+1 rarity tier \(RANDOM new species, keeps level\)/g, 'chaque monstre → +1 rareté (nouvelle espèce ALÉATOIRE, garde le niveau)'],
    [/⚠️ randomizes your board — BREAKS your adopted strategy \/ comp synergies/g, '⚠️ randomise ton board — CASSE ta stratégie adoptée / synergies de compo'],
    [/no committed synergy yet → mostly a raw power-up/g, 'pas encore de synergie engagée → surtout un gain de puissance brut'],
    // 💎 level-up event recommendation picker
    [/💎 Free level — which unit\? \(recommendation below\)/g, '💎 Niveau gratuit — quelle unité ? (recommandation ci-dessous)'],
    [/— which unit to level\? \(recommendation below\)/g, '— quelle unité monter ? (recommandation ci-dessous)'],
    [/👉 Recommended: level /g, '👉 Recommandé : monte '],
    [/it <b>EVOLVES → ([^<]+)<\/b>, a whole power band/g, 'il <b>ÉVOLUE → $1</b>, tout un palier de puissance'],
    [/biggest real output gain for your board/g, 'meilleur gain de sortie réel pour ton board'],
    [/\. Calculated from live day\/team\/trainer\/trinkets\./g, '. Calculé sur jour/équipe/dresseur/trinkets en direct.'],
    [/unlocks ×(\d+) Multicast/g, 'débloque ×$1 Multicast'],
    [/Multicast ×(\d+) — each activation fires \d+× \(matches the game's ×\d+ badge\)/g, 'Multicast ×$1 — chaque activation tire ×$1 (comme le badge ×$1 du jeu)'],
    [/Added by event/g, 'Ajouté par un événement'],
    [/small stat bump/g, 'petite hausse de stats'],
    [/✨ EVOLVES → /g, '✨ ÉVOLUE → '],
    [/♟️ strategy focus/g, '♟️ focus stratégie'], [/🎯 comp piece/g, '🎯 pièce de compo'],
    // synergy header + positioning pills + brain fragments
    [/(\d[\d,]*) ranked runs \/ ([\d,]+) board-rounds/g, '$1 runs classées / $2 manches de board'],
    [/across the top (\d+) leaderboard players \(crawled ([^)]+)\)\. Winners' sample: global round WR is ([\d.]+)%, so compare rows within tables — not against 50%\./g, 'sur les $1 meilleurs joueurs du classement (crawlé $2). Échantillon de gagnants : WR global $3% — compare les lignes entre elles, pas à 50%.'],
    [/(\d+) units removed from the current game version \(([^)]*)\) are filtered out of every table and advice surface\./g, '$1 unités retirées de la version actuelle ($2) sont filtrées de toutes les tables et conseils.'],
    [/(\d+) monsters · full 6-unit boards only \(([\d,]+) rounds\) · enemies to the RIGHT/g, '$1 monstres · boards complets (6) uniquement ($2 manches) · ennemis à DROITE'],
    [/(\d+) combos · real layouts from full 6-unit boards · enemies to the RIGHT/g, '$1 combos · placements réels des boards complets · ennemis à DROITE'],
    [/\(\+([\d.]+) DPS from positioning\) — move units and this updates\./g, '(+$1 DPS grâce au placement) — déplace des unités et ça se met à jour.'],
    [/Casts = activations in the expected battle \((\d+)s ÷ cooldown\); ×N = multicast hits per activation \(already in per-cast values\)\. Poison also shows estimated ramp damage\. Trinket & Chef modifiers included\./g, 'Casts = activations dans le combat attendu ($1s ÷ recharge) ; ×N = coups multicast par activation (déjà dans les valeurs par cast). Le poison montre aussi les dégâts de montée estimés. Modificateurs trinkets & Chef inclus.'],
    // ⚡ CDS column + donation summary
    [/Cooldown speed handed to allies \(Boomagon-style donors\)/g, 'Vitesse de recharge donnée aux alliés (donneurs type Boomagon)'],
    [/Column totals sum each unit's fight-total\. Damage column = direct only; Σ dmg adds each unit's burn\/poison\/shock share \(status is attributed to the unit APPLYING it\)\. ⚡ CDS = permanent cooldown-speed donated this fight\./g, 'Les totaux de colonne additionnent le total par unité sur le combat. Colonne Damage = direct uniquement ; Σ dmg ajoute la part burn/poison/shock de chaque unité (le statut est attribué à l’unité qui l’APPLIQUE). ⚡ CDS = vitesse de recharge permanente donnée ce combat.'],
    [/Cooldown speed this round/g, 'Vitesse de recharge ce tour'],
    [/ — split across units; stack donors behind ONE carry to floor its cooldown faster\./g, ' — réparti sur plusieurs unités ; empile les donneurs derrière UN SEUL carry pour plancher sa recharge plus vite.'],
    [/ — stack donors behind ONE carry to floor its cooldown faster\./g, ' — empile les donneurs derrière UN SEUL carry pour plancher sa recharge plus vite.'],
    [/\(([\d.]+)% over (\d+) rounds\) — yours sits ([a-z·A-Z]+)( \(([\d.]+)%\))?\. Data hint; donor arrows above outrank it\./g, '($1% sur $2 manches) — le tien est en $3$4. Indice de données ; les flèches de donneurs priment.'],
    [/Pick a build in the/g, 'Choisis un build dans l’onglet'],
    [/tab \("Set as run plan"\) — the cockpit will track every piece you're missing and the advisor will hunt them\./g, '(« Définir comme plan de run ») — le cockpit suivra chaque pièce manquante et le conseiller les chassera.'],
    [/🌊 Free random Water Batomon every day \(odds follow your shop rank\)\. Keep bench space; Torrantler turns the stream into a win condition\./g, '🌊 Un Batomon Eau gratuit chaque jour (selon ton rang de boutique). Garde de la place ; Torrantler transforme le flux en win condition.'],
    [/Trainer: ([A-Za-z' ]+?) \(([\d.]+)% WR\) · (Easy|Medium|Hard|Spicy) · Power /g, 'Dresseur : $1 ($2% WR) · $3 · Puissance '],
    [/Pulled from the Steam news feed for Batomon Showdown \(main \+ demo apps\) via the local server, cached 10 min\. Optional: run/g, 'Tiré du flux Steam de Batomon Showdown (app principale + démo) via le serveur local, cache 10 min. Optionnel : lance'],
    [/to also mirror the game's Discord announcements here \(setup instructions in the file\)\./g, 'pour refléter aussi les annonces Discord du jeu ici (instructions dans le fichier).'],
    [/from batodex\.com\. Click trinkets below to add them as your current gift options, then compare\./g, 'depuis batodex.com. Clique les trinkets ci-dessous pour les ajouter comme options de cadeau, puis compare.'],
    [/put (.+?) directly to the LEFT of (.+?) \(behind it, same row\)\./g, 'place $1 directement à GAUCHE de $2 (derrière lui, même rangée).'],
    [/put (.+?) directly to the RIGHT of (.+?) \(in front of it, same row\)\./g, 'place $1 directement à DROITE de $2 (devant lui, même rangée).'],
    [/(\S+) in the BOTTOM row, (.+?) directly ABOVE it \(same column\)\./g, '$1 sur la rangée du BAS, $2 juste AU-DESSUS (même colonne).'],
    [/keep (.+?) touching (.+?) \(middle slots maximize neighbours\)\./g, 'garde $1 au contact de $2 (les cases centrales maximisent les voisins).'],
    [/already positioned\./g, 'déjà bien placé.'],
    [/(\S+) casts ~(\d+)× in ~(\d+)s:/g, '$1 cast ~$2× en ~$3s :'],
    [/≈ \+(\d+)% CDS by fight end \(avg \+(\d+)%\) → ~\+([\d.]+) DPS/g, '≈ +$1% de vitesse en fin de combat (moy. +$2%) → ~+$3 DPS'],
    [/≈ ([\d.]+) extra casts → ~\+(\d+) damage this fight/g, '≈ $1 casts en plus → ~+$2 dégâts ce combat'],
    [/≈ (\d+) bonus casts of (\S+) → ~\+(\d+) damage/g, '≈ $1 casts bonus de $2 → ~+$3 dégâts'],
    [/≈ \+(\d+) Poison stacks → ~\+(\d+) damage over the fight \(ramps\)/g, '≈ +$1 stacks de Poison → ~+$2 dégâts sur le combat (montée)'],
    [/≈ \+(\d+) Burn by fight end/g, '≈ +$1 Brûlure en fin de combat'],
    [/doubles (\S+)'s Shock output/g, 'double le Shock de $1'],
    [/(\S+) is near the 1s cooldown floor — CDS is nearly wasted, stop greeding it here\./g, '$1 est proche du plancher de 1s — la vitesse est quasi gâchée, arrête de greed ici.'],
    // greed meter tails
    [/\((\d+) ❤, \+(\d+)%\): bank permanent ramps — CDS stacks, Bambudo-style permanents, sell-value\. They pay across the ~(\d+) battles left\./g, '($1 ❤, +$2%) : encaisse les rampes permanentes — stacks de vitesse, permanents façon Bambudo, sell-value. Ça paie sur les ~$3 combats restants.'],
    [/\((\d+) ❤, (-?\d+)%\): you can afford ~(\d+) more losses\. Tempo now — shields front, carry crowned top-middle, spend to zero\. Ramp buys nothing if the run ends\./g, '($1 ❤, $2%) : tu peux encaisser ~$3 défaites max. Tempo tout de suite — boucliers devant, carry couronné haut-milieu, dépense tout. La rampe ne vaut rien si la run s’arrête.'],
    [/\((\d+) ❤\): take positioning moves below; only greed ramps that ALSO add tempo this fight\./g, '($1 ❤) : applique les placements ci-dessous ; ne greed que les rampes qui ajoutent AUSSI du tempo ce combat.'],
    // battle brain misc
    [/but the fight ends ~(\d+)s: too short, add tempo or triggers/g, 'mais le combat finit vers ~$1s : trop court, ajoute du tempo ou des triggers'],
    [/model \+ real day-(\d+) enemy averages \((\d+) top-rank boards\)/g, 'modèle + moyennes réelles des ennemis j$1 ($2 boards du top)'],
    // trainer panels (composite sentences)
    [/Free copies so far: /g, 'Copies gratuites reçues : '],
    [/ \(next lands /g, ' (la prochaine arrive '],
    [/\)\. Copies auto-merge 3-to-1 \(3 → Lv 2, 9 → Lv 3\) — free copies \+ bought dups make this your easiest merge line\./g, '). Les copies fusionnent 3 pour 1 (3 → N2, 9 → N3) — copies gratuites + doublons achetés en font ta ligne de fusion la plus facile.'],
    [/Shop priority: every (\S+) you buy compounds the free stream — the advisor boosts it\./g, 'Priorité boutique : chaque $1 acheté compose avec le flux gratuit — le conseiller le booste.'],
    [/First Bug you buy this round is FREE/g, 'Le premier Bug acheté cette manche est GRATUIT'],
    [/ — Bug offers in the shop show \$0 and rank accordingly\./g, ' — les offres Bug affichent 0$ et sont classées en conséquence.'],
    [/First-bug discount used this round — Bug offers show normal prices\. Resets on next day\./g, 'Réduction premier-Bug utilisée cette manche — prix normaux. Réinitialisée demain.'],
    [/Chef converts /g, 'Le Chef convertit les unités '],
    [/single-typed/g, 'mono-types'],
    [/ units to Fire \(\+2 Burn on all Fire\)\. On your board now: /g, ' en Feu (+2 Brûlure sur tout le Feu). Sur ton board : '],
    [/none yet/g, 'aucune pour l’instant'],
    [/Hover any unit — converted typing and the \+2 Burn are shown in its stat card\. Dual-typed units do NOT convert\./g, 'Survole une unité — la conversion et le +2 Brûlure sont dans sa carte de stats. Les bi-types ne convertissent PAS.'],
    [/🎸 Bonus /g, '🎸 Bonus '],
    [/: (\S+) has \+150% Shock\. Do NOT add a second Electric\./g, ' : $1 a +150% Shock. N’ajoute PAS de deuxième Électrik.'],
    [/[—–-] add exactly ONE Electric carry to turn on \+150% Shock\./g, '— ajoute EXACTEMENT UN carry Électrik pour activer le +150% Shock.'],
    [/^idle$/g, 'inactif'], [/^ON$/g, 'ACTIF'], [/^OFF$/g, 'COUPÉ'],
    [/ — (\d+) Electrics on board\. Sell down to exactly one\./g, ' — $1 Électrik sur le board. Revends pour n’en garder qu’un.'],
    [/⚗️ Day-7 transform: your ACTIVE team becomes random L1 Legendaries in /g, '⚗️ Transformation du j7 : ton équipe ACTIVE devient des Légendaires N1 aléatoires dans '],
    [/(\d+) empty slots? = wasted Legendaries — fill them by day 6!/g, '$1 case(s) vide(s) = Légendaires gaspillés — remplis-les avant le jour 6 !'],
    [/All 6 slots filled ✓/g, 'Les 6 cases sont remplies ✓'],
    [/🎭 New mask choice every 4 days \(next: /g, '🎭 Nouveau masque tous les 4 jours (prochain : '],
    [/\)\. Pick the copied trainer above — its full logic \(pricing, boosts, panels\) applies here\./g, '). Choisis le dresseur copié ci-dessus — toute sa logique (prix, boosts, panneaux) s’applique ici.'],
    [/Copied: /g, 'Copié : '],
    [/ — advisor scores with it\./g, ' — le conseiller score avec.'],
    [/🥚 Purple Egg hatches /g, '🥚 Le Purple Egg éclot '],
    [/🎁 Mythical monster \+ \$30 lands /g, '🎁 Monstre Mythique + 30$ arrivent '],
    [/day (\d+)/g, 'jour $1'],
    [/(\d+) days? left/g, '$1 jour(s) restant(s)'],
    [/(\d+) days? away/g, 'dans $1 jour(s)'],
    // mulligan/reroll verdict fragments (split across <b> boundaries)
    [/completes a proven combo — buy it before touching reroll/g, 'complète un combo éprouvé — achète-le avant de penser au reroll'],
    [/nothing here is affordable at \$(\d+) — a fresh roll can offer cheaper value/g, 'rien d’abordable à $$$1 — un nouveau tirage peut offrir de la valeur moins chère'],
    [/a fresh shop's expected best \(~(\d+)%\) beats your current best/g, 'le meilleur attendu d’une boutique fraîche (~$1%) bat ton meilleur actuel'],
    [/\(~(\d+)%\) — ~(-?\d+)% better/g, '(~$1%) — ~$2% mieux'],
    [/\(~(\d+)%\) — ([\d.]+)× stronger on average/g, '(~$1%) — $2× plus fort en moyenne'],
    [/🎲 no roll — it WILL hit/g, '🎲 pas de tirage — ça touchera'],
    [/\(only eligible target\)/g, '(seule cible éligible)'],
    [/it would eat (.+?) — your only Common is worth more than an average random Uncommon/g, 'ça mangerait $1 — ton seul Common vaut plus qu’un Uncommon aléatoire moyen'],
    [/average random Uncommon beats your (average )?Commons? ?(\(.+?\))? by ~(\d+)% — good trade(, roll odds below)?/g, 'un Uncommon aléatoire moyen bat te(s) Common(s) $2 de ~$3% — bon échange$4'],
    [/roughly a coin-flip trade vs an average Uncommon — use it on a throwaway Common, not a keeper/g, 'échange pile-ou-face vs un Uncommon moyen — utilise-le sur un Common jetable, pas un pilier'],
    [/outvalue an average random Uncommon — don't feed the stone/g, 'valent plus qu’un Uncommon aléatoire moyen — ne nourris pas la pierre'],
    [/is fine, but the shop tail is weak — expected fresh roll ~(-?\d+)% better; take the pick, reroll the rest if gold allows/g, 'tient la route, mais le reste de la boutique est faible — tirage frais attendu ~$1% meilleur ; prends-le, puis reroll le reste si l’or le permet'],
    [/\(~(\d+)%\) already matches or beats a fresh roll's expectation \(~(\d+)%\)\./g, '(~$1%) égale ou bat déjà l’attendu d’un tirage frais (~$2%).'],
    [/expected fresh-roll best ≈(\d+)% vs current best (.+?) ≈(\d+)%\./g, 'meilleur attendu d’un reroll ≈$1% vs meilleur actuel $2 ≈$3%.'],
    [/promoted from bench:/g, 'promus depuis le banc :'],
    [/✅ Positioned optimally/g, '✅ Positionné au mieux'], [/🎯 Target layout/g, '🎯 Disposition cible'],
    // strategy plays
    [/♟️ Strategy plays/g, '♟️ Coups stratégiques'],
    [/· engines detected in YOUR state — adopt one and the whole advisor re-aims behind it/g, '· moteurs détectés dans TON état — adoptes-en un et tout le conseiller se réaligne derrière'],
    [/▶ Adopt/g, '▶ Adopter'], [/✓ ACTIVE — drop/g, '✓ ACTIF — lâcher'],
    [/🎯 focus: /g, '🎯 focus : '],
    [/— once adopted, the optimizer concentrates CDS\/donations on it instead of maximizing raw damage/g, '— une fois adopté, l’optimiseur concentre CDS/dons dessus au lieu de maximiser les dégâts bruts'],
    [/is ACTIVE \(its trigger left the shop — still steering buys\/sells\/positioning\)\./g, 'est ACTIF (son déclencheur a quitté la boutique — il pilote toujours achats/ventes/placements).'],
    [/No engine plays detected in the current shop\/board\./g, 'Aucun moteur détecté dans la boutique/board actuels.'],
    [/♟️ Strategy piece — your adopted play/g, '♟️ Pièce de stratégie — ton coup adopté'],
    [/♟️ Strategy food — feeds your adopted play/g, '♟️ Nourriture de stratégie — alimente ton coup adopté'],
    [/optimized FOR/g, 'optimisé POUR'],
    [/\(♟️ strategy focus — donations concentrated, not raw damage\)/g, '(♟️ focus stratégie — dons concentrés, pas dégâts bruts)'],
    [/— ♟️ strategy focus: donations concentrated on it, not raw team damage\./g, '— ♟️ focus stratégie : les dons sont concentrés dessus, pas les dégâts bruts.'],
    [/receiving almost nothing — 🧲 re-optimize to feed it/g, 'ne reçoit presque rien — 🧲 ré-optimise pour le nourrir'],
    [/📋 Strategy plan — do it in this order:/g, '📋 Plan de stratégie — dans cet ordre :'],
    [/📋 No strategy pieces in THIS shop — 🎲 reroll targets: /g, '📋 Aucune pièce de stratégie dans CETTE boutique — 🎲 cibles de reroll : '],
    [/sell <b>(.+?)<\/b> \((.+?)\) — makes room( and adds gold toward the next buy)?/g, 'vends <b>$1</b> ($2) — libère une case$3'],
    [/ and adds gold toward the next buy/g, ' et ajoute de l’or pour l’achat suivant'],
    [/buy <b>(.+?)<\/b> \(−\$(\d+) → \$(\d+) left\)/g, 'achète <b>$1</b> (−$$$2 → $$$3 restants)'],
    [/⚠️ \$(\d+) short for <b>(.+?)<\/b> — sell <b>(.+?)<\/b> \((.+?)\) first; if the sale doesn't cover it, 🔒 lock and buy tomorrow \(\+\$(\d+)\)/g, '⚠️ $$$1 manquants pour <b>$2</b> — vends <b>$3</b> ($4) d’abord ; si la vente ne suffit pas, 🔒 verrouille et achète demain (+$$$5)'],
    [/⚠️ \$(\d+) short for <b>(.+?)<\/b> and nothing safe to sell — 🔒 lock the shop, tomorrow's \+\$(\d+) covers it/g, '⚠️ $$$1 manquants pour <b>$2</b> et rien de sûr à vendre — 🔒 verrouille la boutique, le +$$$3 de demain couvre'],
    [/— the optimizer now concentrates the chain\/donations on/g, '— l’optimiseur concentre maintenant la chaîne/les dons sur'],
    [/\(your Chef BURN carry — CDS multiplies its burn application: the two engines stack\)/g, '(ton carry BURN du Chef — la CDS multiplie son application de brûlure : les deux moteurs s’empilent)'],
    [/Once (.+?) sits near the ~1s floor, ROTATE the chain to the next carry, then sell the Boomagons\./g, 'Quand $1 approche le plancher ~1s, FAIS TOURNER la chaîne vers le carry suivant, puis revends les Boomagon.'],
    [/is at ([\d.]+)s — near the floor: ROTATE the chain to/g, 'est à $1s — proche du plancher : FAIS TOURNER la chaîne vers'],
    [/is at ([\d.]+)s — near the floor: chain done, consider selling the Boomagons\./g, 'est à $1s — proche du plancher : chaîne terminée, pense à revendre les Boomagon.'],
    [/is NOT on the board — field it/g, 'n’est PAS sur le board — aligne-le'],
    [/donated output/g, 'd’output donné'],
    [/where it stands ✓/g, 'là où il est ✓'],
    [/✅ No urgent sale/g, '✅ Pas de vente urgente'],
    [/— everyone's earning their slot/g, '— tout le monde mérite sa case'],
    [/\((\d) free slots? left\)/g, '($1 case(s) libre(s))'],
    [/Cut order if you ever need room: /g, 'Ordre de coupe si tu as besoin de place : '],
    [/Build up a roster first — sell logic kicks in from 2 units\./g, 'Construis d’abord un roster — la logique de vente démarre à 2 unités.'],
    [/, dup,/g, ', doublon,'],
    [/leveled units and hatching eggs are protected/g, 'les unités montées et les œufs qui couvent sont protégés'],
    [/preview applied — make these moves IN GAME; sync will confirm each ✓ on the 🎯 tracker below\./g, 'aperçu appliqué — fais ces mouvements EN JEU ; la sync confirmera chaque ✓ sur le tracker 🎯 en dessous.'],
    [/· multi-round engines the per-pick % undersells/g, '· moteurs multi-rounds que le % par achat sous-estime'],
    [/Boomagon chain/g, 'Chaîne Boomagon'],
    [/\((\d) in shop(, (\d) owned)?, \$(\d+)\): line them up/g, '($1 en boutique$2, $$$4) : aligne-les'],
    [/, (\d) owned/g, ', $1 possédé(s)'],
    [/behind each other, behind/g, 'l’un derrière l’autre, derrière'],
    [/— the back one accelerates the front one's donations, compounding permanent CDS on your carry\./g, '— celui de derrière accélère les dons de celui de devant : CDS permanent composé sur ton carry.'],
    [/WORTH A SHOT/g, 'ÇA VAUT LE COUP'],
    [/— (\d+) ❤ and ~(\d+) battles left to amortize the permanent CDS; sell the Boomagons once (.+?) is fast enough/g, '— $1 ❤ et ~$2 combats pour amortir le CDS permanent ; revends les Boomagon quand $3 est assez rapide'],
    [/NOT NOW/g, 'PAS MAINTENANT'],
    [/: permanent ramps don't pay if the run ends first/g, ' : les rampes permanentes ne paient pas si la run s’arrête avant'],
    [/The optimizer & Brain now model the cascade \(⛓️ in the donor feed\)\./g, 'L’optimiseur & le Brain modélisent la cascade (⛓️ dans le flux des donneurs).'],
    [/Dracana charges the ally BEHIND every cast — put it in front of a Boomagon-style donor and the whole chain speeds up\./g, 'Dracana charge l’allié DERRIÈRE à chaque cast — mets-le devant un donneur type Boomagon et toute la chaîne accélère.'],
    [/\+(\d+)% locked in — go win/g, '+$1% verrouillé — va gagner'],
    [/layout locked — go win/g, 'disposition verrouillée — va gagner'],
    [/🎯 Preview applied/g, '🎯 Aperçu appliqué'],
    [/now make these moves IN GAME; the game's next update confirms the ✅/g, 'fais maintenant ces mouvements EN JEU ; la prochaine mise à jour du jeu confirme le ✅'],
    [/\+(\d+)% when matched · (\d)\/6 in place — move the rest IN GAME, sync follows/g, '+$1% une fois en place · $2/6 posés — bouge le reste EN JEU, la sync suit'],
    [/from bench: /g, 'depuis le banc : '],
    [/🎯 target: (.+?) belongs here/g, '🎯 cible : $1 va ici'],
    [/🎯 target: this slot should be empty/g, '🎯 cible : cette case doit rester vide'],
    [/⚔️ LIVE BATTLE SYNC/g, '⚔️ SYNC COMBAT LIVE'],
    // sell advice + sync-owned endDay
    [/Board & bench/g, 'Board & banc'], [/— sell/g, '— vends'],
    [/\((.+?), your weakest at ~(\d+)% of roster average\) to make room for/g, '($1, ton plus faible à ~$2% de la moyenne du roster) pour faire de la place à'],
    [/Gold crunch at \$(\d+):/g, 'Crise d’or à $$$1 :'],
    [/SWAP\?/g, 'ÉCHANGE ?'], [/SWAP worth it:/g, 'ÉCHANGE rentable :'],
    [/you own (\d+) copies — losing one keeps the merge line/g, 'tu as $1 copies — en perdre une garde la ligne de fusion'],
    [/one of (\d+) copies/g, 'une de $1 copies'],
    [/it's an ENGINE:/g, 'c’est un MOTEUR :'],
    [/⚠️ You're/g, '⚠️ Il te manque'], [/short<\/b> at \$(\d+) — only commit if the sale covers it, otherwise 🔒 lock the shop and buy tomorrow \(\+\$(\d+) income\)\./g, '</b> à $$$1 — n’y va que si la vente couvre, sinon 🔒 verrouille la boutique et achète demain (+$$$2 de revenu).'],
    [/nothing in shop clearly beats your roster; if you need a slot,/g, 'rien en boutique ne bat clairement ton roster ; s’il te faut une case,'],
    [/is the cut\./g, 'est la coupe.'],
    [/NO USES LEFT today \((\d+)\/(\d+)\) — the limit refills tomorrow \(Berroon raises it\)\./g, 'PLUS D’UTILISATIONS aujourd’hui ($1/$2) — la limite se recharge demain (Berroon l’augmente).'],
    [/· feeds (.+?) \(\+(\d+) (.+?) per use\)/g, '· nourrit $1 (+$2 $3 par utilisation)'],
    [/· uses today: (\d+)\/(\d+)/g, '· utilisations aujourd’hui : $1/$2'],
    [/is ~(\d+)% of your average unit — selling it buys tempo NOW instead of waiting a day\./g, 'vaut ~$1% de ton unité moyenne — la vendre achète du tempo MAINTENANT au lieu d’attendre un jour.'],
    [/banks sell value — from day (\d+) it's a piggy bank: cash it when you need the slot or the gold spike\./g, 'accumule de la sell value — depuis le jour $1 c’est une tirelire : encaisse quand tu as besoin de la case ou d’un pic d’or.'],
    [/has farmed its trinkets — it sells for \$20; late game the slot is worth more than the heals\./g, 'a farmé ses trinkets — ça se vend $20 ; en fin de partie la case vaut plus que les heals.'],
    [/⚡ Game sync records battles automatically — day, gold, lives, badges and history follow the game\. Turn sync OFF to drive manually\./g, '⚡ La sync enregistre les combats automatiquement — jour, or, vies, badges et historique suivent le jeu. Coupe la sync pour piloter à la main.'],
    [/— simulating vs/g, '— simulation contre'],
    [/, their actual board:/g, ', leur board réel :'],
    [/^⚔️ THEIR board$/g, '⚔️ LEUR board'],
    [/☠️ Their biggest threats:/g, '☠️ Leurs plus grosses menaces :'],
    [/— burst or outlast accordingly\./g, '— burst ou endurance en conséquence.'],
    [/matched opponent/g, 'adversaire matché'],
    [/the REAL matched opponent \(battle sync — their board, donors and ramps fully modeled\)/g, 'le VRAI adversaire matché (sync combat — leur board, donneurs et ramps entièrement modélisés)'],
    [/\(\$(\d+)\) is the strongest thing here \(~(\d+)%\) but out of budget — lock the shop, tomorrow's \+\$(\d+) income buys it/g, '($$$1) est le plus fort ici (~$2%) mais hors budget — verrouille la boutique, le revenu de demain (+$$$3) le paie'],
    [/you break their ([\d,]+) HP \(EHP ~([\d,]+)\) in ~(\d+)s, they break your ([\d,]+) \(EHP ~([\d,]+)\) in ~(\d+)s/g, 'tu casses leurs $1 PV (EHP ~$2) en ~$3s, ils cassent tes $4 (EHP ~$5) en ~$6s'],
    [/Σ over ~(\d+)s: you deal/g, 'Σ sur ~$1s : tu infliges'],
    [/into their EHP ~([\d,]+)/g, 'dans leur EHP ~$1'],
    [/into your EHP ~([\d,]+)/g, 'dans ton EHP ~$1'],
    [/✗ (\d+)% there/g, '✗ $1% du chemin'], [/✓ you survive/g, '✓ tu survis'], [/✗ you die/g, '✗ tu meurs'], [/^✓ kill$/g, '✓ kill'],
    [/they deal/g, 'ils infligent'],
    [/^Σ dmg ~(\d+)s$/g, 'Σ dégâts ~$1s'],
    [/status damage attributed to the unit APPLYING it; positional donor bonuses are in the team totals above/g, 'dégâts de statut attribués à l’unité qui les APPLIQUE ; les bonus positionnels des donneurs sont dans les totaux d’équipe ci-dessus'],
    [/Σ dmg = direct \+ the unit's burn\/poison\/shock damage over ~(\d+)s \(hover it for the split\)\./g, 'Σ dégâts = directs + brûlure/poison/shock de l’unité sur ~$1s (survole pour le détail).'],
    [/⚡ Shock \(wiki-exact\): every direct hit deals/g, '⚡ Shock (exact wiki) : chaque coup direct inflige'],
    [/flat damage — by fight end you'll have ~/g, 'dégâts plats — en fin de combat tu auras ~'],
    [/stacks on them, so your ~([\d.]+) hits\/s gain up to/g, 'stacks sur eux, donc tes ~$1 coups/s gagnent jusqu’à'],
    [/late\. More hits\/s \(multicast, CDS\) multiplies shock\./g, 'en fin de combat. Plus de coups/s (multicast, vitesse) multiplie le shock.'],
    [/\(averaged over the expected fight, already in the totals\):/g, '(moyennés sur le combat attendu, déjà dans les totaux) :'],
    [/: \+(\d+)% CDS\/cast → avg CD ~([\d.]+)s \((\d+) casts\)/g, ' : +$1% CDS/cast → CD moyen ~$2s ($3 casts)'],
    [/\/cast → avg \+(\d+) by mid-fight \((\d+) casts/g, '/cast → +$1 en moyenne à mi-combat ($2 casts'],
    [/, permanent — snowballs across the run/g, ', permanent — boule de neige sur toute la run'],
    [/: feeds on your ([\d.]+) Shield\/s → ~\+([\d.]+) avg DPS/g, ' : se nourrit de tes $1 Bouclier/s → ~+$2 DPS moyen'],
    [/Dmg per ally poison proc \(([\d.]+)\/s\) → ramps hard/g, 'Dmg par proc de poison allié ($1/s) → grosse montée'],
    [/: charged by ([\d.]+) shock procs\/s → casts ×([\d.]+)/g, ' : chargé par $1 procs de shock/s → casts ×$2'],
    // build path + item rolls
    [/Build path — /g, 'Chemin de build — '],
    [/: (\d+)\/(\d+) pieces owned\./g, ' : $1/$2 pièces possédées.'],
    [/Next piece/g, 'Prochaine pièce'],
    [/\(simulated at L1 in your empty slot\)/g, '(simulé N1 dans ta case vide)'],
    [/board full, decide who it replaces\./g, 'board plein, choisis qui elle remplace.'],
    [/🛒 IN SHOP NOW\./g, '🛒 DANS LA BOUTIQUE.'],
    [/Complete ✓ — pivot gold to levels, shinies and trinkets\./g, 'Complet ✓ — bascule l’or vers niveaux, shinies et trinkets.'],
    [/(\d+) eligible · ([\d.]+)% each — /g, '$1 éligibles · $2% chacun — '],
    [/best roll:/g, 'meilleur tirage :'], [/worst roll:/g, 'pire tirage :'],
    [/middle: (\d+) others in the middle/g, 'milieu : $1 autres'], [/middle: /g, 'milieu : '],
    [/transforms a random Common into an Uncommon — a fed\/leveled\/plan one is the worst loss/g, 'transforme un Common aléatoire en Uncommon — un nourri/niveau élevé/pièce du plan est la pire perte'],
    [/levels a random L1 Common\/Uncommon — best roll = biggest L2 jump \(merge\/evo progress\)/g, 'monte un N1 Common/Uncommon aléatoire — meilleur tirage = plus gros saut N2 (fusion/évo)'],
    [/a random monster FROM THIS SHOP — best\/worst follow the buy advice ranking/g, 'un monstre aléatoire DE CETTE BOUTIQUE — meilleur/pire suivent le classement d’achat'],
    [/\+5 damage to two random units — best on fast multicasters, dead on pure supports/g, '+5 dégâts à deux unités aléatoires — top sur les multicasts rapides, nul sur les purs supports'],
    // batodex hub notes + sync pill
    [/All (\d+) shop items — curated tier \+ live buy logic feeds the cockpit's 🧪 Item advice\./g, 'Les $1 objets de boutique — tier curaté + logique d’achat live alimentent le 🧪 Conseil objets du cockpit.'],
    [/All (\d+) trinkets — official win\/pick rates \+ Master-run held-WR from the crawl\. Compare gift options in the/g, 'Les $1 trinkets — win/pick rates officiels + WR-porté des runs Master. Compare tes cadeaux dans l’onglet'],
    [/All (\d+) trainers — real Master Ranked win\/pick rates\. The cockpit's trainer panel activates each one's full logic\./g, 'Les $1 dresseurs — win/pick rates réels en Master. Le panneau dresseur du cockpit active la logique de chacun.'],
    [/All (\d+) events with their real options — hit one in-game\? The cockpit's 🎪 Event advisor scores every choice for YOUR board\./g, 'Les $1 événements avec leurs vraies options — croisé en jeu ? Le 🎪 Conseiller d’événements note chaque choix pour TON board.'],
    [/All (\d+) Batomon — click a card for levels, abilities, real placement & win-rate data\./g, 'Les $1 Batomon — clique une carte pour niveaux, capacités, placements réels & win rates.'],
    [/held-WR at Master \(([\d,\s]+) rounds\)/g, 'WR-porté en Master ($1 manches)'],
    [/official ([\d.]+)% WR · ([\d.]+)% picked/g, 'officiel $1% WR · $2% pick'],
    [/— no active run/g, '— pas de run active'],
    [/🌱 fed:/g, '🌱 nourri :'], [/🌱 permanent:/g, '🌱 permanent :'],
    // targeted (bottom-right) items
    [/🎯 hits the/g, '🎯 touche la case'], [/ slot \(/g, ' ('],
    [/use NOW/g, 'utilise MAINTENANT'],
    [/standing there is already the best target \(\+(\d+) output\)/g, 'déjà en place est la meilleure cible (+$1 output)'],
    [/best target:/g, 'meilleure cible :'],
    [/, on bench\)/g, ', sur le banc)'],
    [/currently there: /g, 'actuellement là : '],
    [/→ swap (.+?) in first/g, '→ échange $1 d’abord'],
    [/slot is EMPTY → move (.+?) there first/g, 'case VIDE → place $1 d’abord'],
    [/· runner-up: /g, '· second : '],
    [/turns a RANDOM non-shiny monster shiny — best roll = biggest shiny upgrade \(upgraded abilities count\)/g, 'rend SHINY un monstre non-shiny ALÉATOIRE — meilleur tirage = plus gros saut shiny (capacités améliorées comptent)'],
    [/\+20 Sell Value on a random monster — jackpot on sell-value scalers, shrug elsewhere/g, '+20 Sell Value sur un monstre aléatoire — jackpot sur les scalers de sell value, bof ailleurs'],
    [/\+1 Multicast to a random damage-dealer — best roll = your hardest hitter/g, '+1 Multicast sur un attaquant aléatoire — meilleur tirage = ton plus gros frappeur'],
    [/\(fed\+trinkets\)/g, '(nourri+trinkets)'], [/^\(fed\)$/g, '(nourri)'],
  ];

  function trText(str) {
    const trimmed = str.trim();
    if (!trimmed) return str;
    if (EXACT[trimmed] != null) return str.replace(trimmed, EXACT[trimmed]);
    for (const [re, rep] of PATTERNS) {
      if (re.test(str)) return str.replace(re, rep);          // raw — handles space-anchored fragments
      if (re.test(trimmed)) return str.replace(trimmed, trimmed.replace(re, rep)); // trimmed
    }
    // composite nodes: apply unanchored patterns anywhere
    let s = str;
    for (const [re, rep] of PATTERNS_INLINE) { re.lastIndex = 0; s = s.replace(re, rep); }
    return s;
  }

  function translateUnder(root) {
    if (lang !== 'fr' || !root) return;
    const scope = root.nodeType === 1 || root.nodeType === 9 ? root : root.parentElement;
    if (!scope) return;
    const walker = document.createTreeWalker(scope, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const n of nodes) {
      const v = trText(n.nodeValue);
      if (v !== n.nodeValue) n.nodeValue = v;
    }
    if (scope.querySelectorAll) {
      scope.querySelectorAll('[title]').forEach(e => { const v = trText(e.getAttribute('title')); if (v !== e.getAttribute('title')) e.setAttribute('title', v); });
      scope.querySelectorAll('[placeholder]').forEach(e => { const v = trText(e.getAttribute('placeholder')); if (v !== e.getAttribute('placeholder')) e.setAttribute('placeholder', v); });
    }
  }

  let obs = null;
  function watch() {
    if (lang !== 'fr') return;
    translateUnder(document.body);
    obs = new MutationObserver((muts) => {
      obs.disconnect();
      for (const m of muts) translateUnder(m.target);
      obs.observe(document.body, { childList: true, subtree: true });
    });
    obs.observe(document.body, { childList: true, subtree: true });
  }

  return {
    get lang() { return lang; },
    set(l) { localStorage.setItem('bc_lang', l); location.reload(); },
    t: (en, fr) => (lang === 'fr' && fr != null ? fr : en),
    watch, translateUnder,
  };
})();
